### ISSUE TITLE
Codist 5.5 Beta Version

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#108]
Download:
[Codist 5123](https://github.com/wmjordan/Codist/files/3930351/Codist.zip)

[Codist 5107](https://github.com/wmjordan/Codist/files/3924673/Codist.zip)
[Codist 5104](https://github.com/wmjordan/Codist/files/3919615/Codist.zip)
[Codist 5093](https://github.com/wmjordan/Codist/files/3906658/Codist.zip)
[Codist 5084](https://github.com/wmjordan/Codist/files/3895046/Codist.zip)
[Codist 5067](https://github.com/wmjordan/Codist/files/3890552/Codist.zip)
[Codist 5058](https://github.com/wmjordan/Codist/files/3855471/Codist.zip)
[Codist 5049](https://github.com/wmjordan/Codist/files/3803147/Codist.zip)
[Codist 5043](https://github.com/wmjordan/Codist/files/3748628/Codist.zip)
[Codist 5029](https://github.com/wmjordan/Codist/files/3726891/Codist.zip)
[Codist 5017](https://github.com/wmjordan/Codist/files/3715219/Codist.zip)
[Codist 5013](https://github.com/wmjordan/Codist/files/3710079/Codist.zip)

What's new in this new beta:

- [x] Symbol Analyzer
   - [x] Added _Find Method with Same Signature_ command (#106)
![新的图片](https://user-images.githubusercontent.com/12182730/69006425-f089cc00-0969-11ea-987d-d7d0973ab573.png)
   - [x] Displayed source code of reference points in tool tips for symbol referrers (b5043)
![新的图片](https://user-images.githubusercontent.com/12182730/69006389-85d89080-0969-11ea-9228-3bf86fecd6fd.png)
   - [x] Fixed _Find Type Referrers_ could fail if an identifier was prefixed by namespaces
   - [x] Enhanced color preview for predefined colors and brushes (5084)
   - [x] Displayed event arguments (b5084)
- [x] Scrollbar Marker
   - [x] Fixed a crash in C# Member Marker (#111,  b5029)
   - [x] Used built-in syntax colors for C# member markers (b5084)
- [x] Super Quick Info
   - [x] Fixed an error about inheriting XML Doc from property indexer parameters
   - [x] Displayed inherited C# `exception` XML Doc
   - [x] Fixed selection color was opaque
   - [x] Used built-in syntax colors when Advance Syntax Highlight was disabled (#113)
   - [x] Fixed syntax colors on Super Quick Info were not updated after syntax configuration changes 
(b5084)
   - [x] Fixed Super Quick Info for `await` keyword could cause error (#117, b5107)
- [x] Syntax Highlight
   - [x] Highlighted `stackalloc` and `unsafe` keywords in declarations (b5043)
   - [x] Classified parentheses of C# `delegate` declarations (b5043)
   - [x] Added support to C# 8 beta
   - [x] Added separated style for C# Enum Fields (b5067)
   - [x] Made user code differentiation compatible with VS 16.5 preview (b5104)
- [x] Smart Bar
   - [x] Tweaked the behavior of Smart Bar
- [x] Navigation Bar
   - [x] Fixed a crash after splitting code document window (#115, b5093)

**Comment by wmjordan** [comment]
@fitdev
I am considering re-implementing something alike #25 (scope guidelines).
However, it should not be triggered automatically, I think, since it can be distracting.
How do you think the way to trigger that function?

**Comment by fitdev** [comment]
Perhaps it can be shown only for the active (inner-most) scope (relative to where cursror is) and be faded at first. Then when the user hovers over it, it could become bright and allow to perform some operations like select the block for example, or display tooltip showing starting and ending lines of the block.

**Comment by fitdev** [comment]
Just started working with Razor recently, and noticed that C# comments in .cshtml (haven't checked the newer .razor) files do not support advanced comment styles that are available for regular .cs files:

![2019-10-29 09_16_46-Window](https://user-images.githubusercontent.com/8166847/67742420-08d28f00-fa2d-11e9-88ac-585a92fdf469.jpg)

In the above example the `TODO:` part should be colored differently as per my comment styles in Codist:

![2019-10-29 09_18_14-Window](https://user-images.githubusercontent.com/8166847/67742485-3ddee180-fa2d-11e9-9196-f6b8b1271228.jpg)

**Comment by wmjordan** [comment]
I was out of business trip these days.
The comment tagger has not supported in cshtml yet. I will upload a new beta version for this later.

**Comment by wmjordan** [comment]
@fitdev I was out of business trip these days.
The comment tagger has not supported in cshtml yet. I will upload a new beta version for this later.

**Comment by wmjordan** [comment]
@fitdev PLEASE try the new beta.

**Comment by fitdev** [comment]
Thanks for the new beta, but I did not notice any changes. What should I look for?

**Comment by wmjordan** [comment]
Oh, that should be a time-consuming problem. I haven't programmed web app for quite a few years. It seems that this issue can not be solved until I install web app support.

**Comment by fitdev** [comment]
Oh I see. Well, it's really minor thing, so don;t worry too much about it. Surprisingly though, other C# highlighting works fine in cshtml files.

**Comment by fitdev** [comment]
A small bug in the comments highlighter:

I have set opacity to 8 (half) under _All languages / Comment_ so that comments are not as bright.
Then I have _Enabled Comment Tagger_ and defined a few custom tags.

The problem: opacity is _not respected_ for these new custom tags. That is, on these new custom comment tags I used the styles where text opacity is at maximum, yet the tags are rendered with opacity of 8 (coming from general comment style). The colors are correct as well as font styles and sizes, but not the opacity.

Strangely the issue affects only _new_ custom tags, for example built-in `TODO` tag is not affected - and is rendered with full opacity, as per the used style.

**Comment by wmjordan** [comment]
Please post your configuration file here. I need it to reproduce the problem.
The priority and inheritance of the syntax styles are quite odd in VS sometimes. I could not yet fully figure out how it operates.

**Comment by fitdev** [comment]
Here's the config file:

[Config.json.zip](https://github.com/wmjordan/Codist/files/3828232/Config.json.zip)

**Comment by wmjordan** [comment]
Thank you for sharing the config file. I am busy with stuff in my hands recently. I will take a look at it when things get handled.

**Comment by fitdev** [comment]
Seems like setting Opacity explicitly to 15 solves the problem. However setting it to 16, causes the program to use default opacity (which is like 7 in my case for comments). So I guess it's a small bug, but not critical one - I can live with 15 instead of 16.

**Comment by wmjordan** [comment]
@fitdev, I reproduced your problem but also found that it was unfortunately quite a tricky issue related to the unresolved #14.

**Comment by fitdev** [comment]
I see. Thank you for looking into this. For now I seem to have found a workaround - setting opacity to 15 seems to make text bright enough to easily stand out for all custom comment tags.

**Comment by wmjordan** [comment]
Please try the new beta to see whether it fix the opacity issue well or not.

**Comment by fitdev** [comment]
Yeas, 5058 seems to have fixed Opacity issue.
I did get VS error bar though upon opening my solution after upgrading to 5058:
```System.NullReferenceException: Object reference not set to an instance of an object.at Microsoft.CodeAnalysis.CSharp.Symbols.SubstitutedPropertySymbol.get_TypeWithAnnotations()at Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.GetTypeOrReturnType(Symbol symbol, RefKind& refKind, TypeWithAnnotations& returnType, ImmutableArray`1& refCustomModifiers)at Microsoft.CodeAnalysis.CSharp.LocalDataFlowPass`1.GetOrCreateSlot(Symbol symbol, Int32 containingSlot, Boolean forceSlotEvenIfEmpty)at Microsoft.CodeAnalysis.CSharp.NullableWalker.GetNullableOfTValueSlot(TypeSymbol containingType, Int32 containingSlot, Symbol& valueProperty, Boolean forceSlotEvenIfEmpty)at Microsoft.CodeAnalysis.CSharp.NullableWalker.LearnFromDecisionDag(SyntaxNode node, BoundDecisionDag decisionDag, BoundExpression expression, TypeWithState expressionType, LocalState& initialState)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitSwitchExpressionCore(BoundSwitchExpression node, Boolean inferType)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitUnconvertedSwitchExpression(BoundUnconvertedSwitchExpression node)at Microsoft.CodeAnalysis.CSharp.BoundUnconvertedSwitchExpression.Accept(BoundTreeVisitor visitor)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitWithStackGuard(BoundNode node)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitAlways(BoundNode node)at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitRvalue(BoundExpression node, Boolean isKnownToBeAnLvalue)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitOptionalImplicitConversion(BoundExpression expr, TypeWithAnnotations targetTypeOpt, Boolean useLegacyWarnings, Boolean trackMembers, AssignmentKind assignmentKind)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitAssignmentOperator(BoundAssignmentOperator node)at Microsoft.CodeAnalysis.CSharp.BoundAssignmentOperator.Accept(BoundTreeVisitor visitor)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitWithStackGuard(BoundNode node)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitAlways(BoundNode node)at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitRvalue(BoundExpression node, Boolean isKnownToBeAnLvalue)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitExpressionStatement(BoundExpressionStatement node)at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitWithStackGuard(BoundNode node)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitAlways(BoundNode node)at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatement(BoundStatement statement)at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitBlock(BoundBlock node)at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitWithStackGuard(BoundNode node)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitAlways(BoundNode node)at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitMethodBodies(BoundBlock blockBody, BoundBlock expressionBody)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node)at Microsoft.CodeAnalysis.CSharp.BoundNonConstructorMethodBody.Accept(BoundTreeVisitor visitor)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitWithStackGuard(BoundNode node)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.VisitAlways(BoundNode node)at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.Scan(Boolean& badRegion)at Microsoft.CodeAnalysis.CSharp.NullableWalker.Scan(Boolean& badRegion)at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`1.Analyze(Boolean& badRegion, Optional`1 initialState)at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(NullableWalker walker, Symbol symbol, DiagnosticBag diagnostics, VariableState initialState, Builder snapshotBuilderOpt)at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, Conversions conversions, DiagnosticBag diagnostics, Boolean useMethodSignatureParameterTypes, MethodSymbol delegateInvokeMethodOpt, VariableState initialState, Builder analyzedNullabilityMapOpt, Builder snapshotBuilderOpt, ArrayBuilder`1 returnTypesOpt)at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeAndRewrite(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols)at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.RewriteNullableBoundNodesWithSnapshots(BoundNode boundRoot, Binder binder, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols)at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.<EnsureNullabilityAnalysisPerformedIfNecessary>g__bindAndRewrite|130_1(<>c__DisplayClass130_0& )at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary()at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node)at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent)at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(Workspace workspace, SyntaxNode syntax, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax)at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, CancellationToken cancellationToken)at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.AddSemanticClassifications(SemanticModel semanticModel, TextSpan textSpan, Workspace workspace, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, ArrayBuilder`1 result, CancellationToken cancellationToken)at Microsoft.CodeAnalysis.Classification.Classifier.GetClassifiedSpans(SemanticModel semanticModel, TextSpan textSpan, Workspace workspace, CancellationToken cancellationToken)at Codist.Taggers.CSharpTagger.<GetTags>d__5.MoveNext() in E:\Codes\Open Source Projects\Codist\Codist\Taggers\CSharpTagger.cs:line 60at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext()
```

But at least it did not crash VS and syntax highlighting seemed to work fine... just the error bar appeared which let me to open VS log.

**Comment by wmjordan** [comment]
Thank you for verifying the new beta.
It is weird to see that exception.
Did that error occur every time you work with VS?
If so, could you create a small project which reproduces this issue?

**Comment by fitdev** [comment]
It happened only once or twice - right after solution load. I will keep an eye on it and let you know (though I do not reload solutions that often).

**Comment by wmjordan** [comment]
Thanks for explaining the problem. I never met with this before, neither in VS 2017 or VS 2019 latest previews.
I will check the code when I have time.

Do you use the preview version of VS 2019?
Maybe it can be a problem of the preview version of Roslyn.

**Comment by fitdev** [comment]
I do use the preview version, but it is not latest at the moment. I will let you know if I encounter this issue again. It's not too important though since it happens rarely and does not crash VS.

**Comment by laicasaane** [comment]
I would like to have class and struct constructors separated, just like what VS is doing.

**Comment by wmjordan** [comment]
> have class and struct constructors separated

@laicasaane How VS is doing this? As far as I know, VS does not highlight constructors.

**Comment by laicasaane** [comment]
Might be true for earlier versions, but the current 2019 version really does that.

![image](https://user-images.githubusercontent.com/1594982/69786685-7f5dda80-11ed-11ea-9a9d-75a70e30a078.png)

**Comment by fitdev** [comment]
@laicasaane I think you can already do that in the Options - Syntax Highlight - All Languages - "Class Name" and "Struct Name". I have set them to different colors for myself and it works well in definitions, constructors and regular usage.

**Comment by wmjordan** [comment]
@fitdev He meant the constructor.
Currently Codist uses a distinct color to denote the constructor.
I set the constructors to be highlighted with a bright orange color to make them stand out of other parts, which is extremely easy to see in the _Scrollbar Marker_.
Let's take a look at the scrollbar in following screen shot.
The orange line segments indicated that there are constructors there, where ordinary methods were drawn in dark red.
![shot](https://user-images.githubusercontent.com/12182730/69847963-9e26a480-12b3-11ea-9638-01ac9d52fb2b.png)

**Comment by fitdev** [comment]
Oh I see. I wasn't actually using any special styles for constructors. Just preferred the distinction between classes vs structs. BTW, thank you for adding enums and enum fields as separate categories and also showing the inheritance tooltips!

**Comment by fitdev** [comment]
Using latest build of Codist and VS 2019 16.5 Preview 1 (just released). It seems that syntax highlighting for framework code vs user code no longer works (user code is no longer differentiated).

**Comment by wmjordan** [comment]
@fitdev, Please use the new beta.

**Comment by fitdev** [comment]
@wmjordan Thanks so much for such a quick fix! It works great now! BTW: For me User Code Differentiation is probably the #1 feature in Codist!

**Comment by wmjordan** [comment]
Good to hear that. I love the User Code Differentiation feature too. Thank you so much for purposing it and making the Syntax Highlighting in Codist so unique.

**Comment by wmjordan** [comment]
@fitdev There was a bug in the previous beta which could crash VS.
Please use the new one.

**Comment by fitdev** [comment]
@wmjordan Thank you. I updated Codist to 5123, though I did not experience any crashes with the previous version.

**Comment by wmjordan** [comment]
Version 5.5 was just released. It will be published to the market place soon.
