### ISSUE TITLE
Codist 5.6 Beta Version

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#118]
> ## **NOTICE**
> The version b5643 used a new format of configuration file to enable customizing EVERY syntax highlight aspects, but it could be **BUGGY**. So, be sure to **SAVE** your config before upgrading to the new beta.

Download:
[Codist 5.6.5648](https://github.com/wmjordan/Codist/files/4668143/Codist.zip)
[Codist 5.6.5643 RC1](https://github.com/wmjordan/Codist/files/4626592/Codist.zip)
[Codist 5620](https://github.com/wmjordan/Codist/files/4602552/Codist.zip)
[Codist 5605](https://github.com/wmjordan/Codist/files/4585060/Codist.zip)
[Codist 5580](https://github.com/wmjordan/Codist/files/4572439/Codist.zip)
[Codist 5540](https://github.com/wmjordan/Codist/files/4569444/Codist.zip)
[Codist 5528](https://github.com/wmjordan/Codist/files/4526014/Codist.zip)
[Codist 5511](https://github.com/wmjordan/Codist/files/4496262/Codist.zip)
[Codist 5493](https://github.com/wmjordan/Codist/files/4435809/Codist.zip)
[Codist 5490](https://github.com/wmjordan/Codist/files/4433586/Codist.zip)
[Codist 5475](https://github.com/wmjordan/Codist/files/4432957/Codist.zip)
[Codist 5464](https://github.com/wmjordan/Codist/files/4407495/Codist.zip)
[Codist 5457](https://github.com/wmjordan/Codist/files/4402081/Codist.zip)
[Codist 5422](https://github.com/wmjordan/Codist/files/4362231/Codist.zip)
[Codist 5399](https://github.com/wmjordan/Codist/files/4357556/Codist.zip)
[Codist 5384](https://github.com/wmjordan/Codist/files/4301265/Codist.zip)
[Codist 5339](https://github.com/wmjordan/Codist/files/4051824/Codist.zip)
[Codist 5330](https://github.com/wmjordan/Codist/files/4048965/Codist.zip)
[Codist 5195](https://github.com/wmjordan/Codist/files/3982916/Codist.zip)
[Codist 5175](https://github.com/wmjordan/Codist/files/3971380/Codist.zip)

What's new in this new beta:
- [x] Options Pages
   - [x] Fixed changing focus in Options Page of Codist Could Freeze Visual Studio (#110, #42, b5330, b5457, b5490)
   - [x] Rewrote the configuration modules, especially for syntax highlighting, created a _Customize Codist Syntax Highlighting_ command in the _Tools_ Menu (#120, b5330, b5339, b5399, b5453, b5490)
- [ ] Symbol Analyzer
   - [x] Tweaked the display of symbol menus (b5175)
   - [x] Changed the Find Methods by Signature command to find and match delegates as well
   - [x] Displayed usage kind icons and more results produced by the Find Referrers command (b5605)
     ![symbol-usage-icon](https://user-images.githubusercontent.com/12182730/82743373-12db2700-9d9d-11ea-91a0-607e6ebbc0f4.png)
   - [x] Fixed a crash when dealing with unsafe pointer access expressions (b5620)
- [ ] Scrollbar Marker
   - [x] Drew markers for C# constructors on scrollbar marker (b5175)
   - [x] Fixed a crash caused by C# Members Margin (b5330, b5399)
- [ ] Syntax Highlight
   - [x] **Allow customizing every syntax highlight styles** (b5643)
   ![all-syntax-configuration](https://user-images.githubusercontent.com/12182730/82743393-63528480-9d9d-11ea-97b6-24d8beebaeb8.png)
    the above dialog can be opened from _Tools/Customize Codist Syntax Highlighting_ menu
   - [x] Slightly optimized the performance of the C# syntax highlighter (b5175)
   - [x] C# comment tagger not working in Razor documents (#116, b5195)
   - [x] Fixed a crash caused by the Comment Tagger (#121, b5330)
   - [x] Classified type of explicit or implicit operator as member declaration (b5384)
   - [x] Added an option to highlight find results in C# code files (#57, b5510)
   - [x] Type cast parentheses highlighted with the same style of type related keywords (b5528)
   - [x] Updated syntax highlight to support C# 8.0 (b5577)
- [x] Super Quick Info
   - [x] Supported `<h1 />` to `<h6 />` in C# XML Doc (b5330)
   - [x] Supported `<a href />` in C# XML Doc (b5330)
   - [x] Support `<see cref="http..." />` linking to web pages in C# XML Doc (b5384)
   - [x] Fixed incomplete display of some items (b5330)
   - [x] Fixed in some cases Color Quick Info was not working (b5330)
   - [x] Supported displaying `<example />` in C# XML Doc (b5384)
   - [x] Displayed namespace in Symbol Location Quick Info for members (b5648, #123)
- [x] Smart Bar
   - [x] Enabled Rename refactoring command for type parameter declarations (b5330)
   - [x] Added a command for extension developers to discover classifiers and taggers results for selections (b5330)
- [x] Navigation Bar
   - [x] Fixed a crash when dealing with unsafe pointer access expressions (b5620)

**Comment by fitdev** [comment]
I noticed that sometimes the TODO comment highlights are not always rendered in the editor for .cs files. I have not noticed a pattern yet. But it may be that in one window, on one monitor, it's working, and in another window (different document) it is not highlighted. Closing and reopening document fixes it.

**Comment by wmjordan** [comment]
Maybe it was the problem caused by an unsuccessful optimization that I'd noticed recently, in another situation.
Please try the **next** beta.

**Comment by fitdev** [comment]
Hi! Hope you are doing well. Just noticed that Codist sometimes would throw this upon VS solution load:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: indexat Microsoft.VisualStudio.Text.NormalizedSnapshotSpanCollection.get_Item(Int32 index)at Codist.Taggers.CommentTagger.<GetTags>d__18.MoveNext() in E:\Codes\Open Source Projects\Codist\Codist\Taggers\CommentTagger.cs:line 105at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext()
```

**Comment by wmjordan** [comment]
@fitdev Please try the new beta--the syntax configuration module is still being developed thus it may have some problems.

**Comment by fitdev** [comment]
Wow! That was so fast! Thank you! Seems to have fixed the issue.

**Comment by wmjordan** [comment]
> Hope you are doing well

Hi @fitdev, thank you very much for your blessing! Our central government had made decisive actions and mobilizations. Fortunately there are few COVID-2019 patients in my town. I have been working at home for two weeks, with many project items in the to-do list as well.

**Comment by fitdev** [comment]
You are very welcome :) Stay safe!

**Comment by wmjordan** [comment]
@fitdev Hey, how are you doing?
The new beta version has a new syntax highlight configuration module, which is still in development. Would you like to give it a try?

**Comment by stecydube** [comment]
I have an exception when opening a cs file.


System.TypeInitializationException: The type initializer for 'Codist.SyntaxHighlight.FormatStore' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.   at Codist.SyntaxHighlight.FormatStore.LoadSyntaxStyleCache(Dictionary`2 cache) in E:\Codes\Open Source Projects\Codist\Codist\SyntaxHighlight\FormatStore.cs:line 155   at Codist.SyntaxHighlight.FormatStore.InitSyntaxStyleCache() in E:\Codes\Open Source Projects\Codist\Codist\SyntaxHighlight\FormatStore.cs:line 147   at Codist.SyntaxHighlight.FormatStore..cctor() in E:\Codes\Open Source Projects\Codist\Codist\SyntaxHighlight\FormatStore.cs:line 16 --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)   --- End of inner exception stack trace ---   at Codist.SyntaxHighlight.FormatStore.get_IdentifySymbolSource() in E:\Codes\Open Source Projects\Codist\Codist\SyntaxHighlight\FormatStore.cs:line 22   at Codist.Taggers.CSharpTagger.<GetClassificationType>d__10.MoveNext() in E:\Codes\Open Source Projects\Codist\Codist\Taggers\CSharpTagger.cs:line 631   at Codist.Taggers.CSharpTagger.<GetTags>d__5.MoveNext() in E:\Codes\Open Source Projects\Codist\Codist\Taggers\CSharpTagger.cs:line 212   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext()
--

Furthermore, I tried to compile the extension from the source code but there are compiler errors. Also, is the repository containing the sources of the beta?

**Comment by wmjordan** [comment]
@stecydube 
The repository does contain the sources of the beta, but some code files which have some premature features might not have been committed, thus you may encounter errors.
Please try the new beta (b5538) I've uploaded just now and see whether it fixes your problem.

**Comment by stecydube** [comment]
Got the same exception. :(

**Comment by stecydube** [comment]
Here are the compiler errors:

Severity|Code|Description|Project|File|Line|Suppression State
--|--|--|--|--|--|--
Error|CS0534|'CustomTagger' does not implement inherited abstract member 'CachedTaggerBase.Parse(SnapshotSpan, ICollection&lt;TaggedContentSpan&gt;)'|Codist|C:\dev\Perso\Codist\Codist\Taggers\CustomTagger.cs|12|Active
Error|CS0115|'CustomTagger.Parse(SnapshotSpan)': no suitable method found to override|Codist|C:\dev\Perso\Codist\Codist\Taggers\CustomTagger.cs|22|Active
Error|CS0101|The namespace 'Codist.Taggers' already contains a definition for 'ITextTagger'|Codist|C:\dev\Perso\Codist\Codist\Taggers\Interfaces.cs|14|Active
Error|CS0205|Cannot call an abstract base member: 'Singer.Sing(string, params string[])'|TestProject|C:\dev\Perso\Codist\TestProject\InheritDoc.cs|104|Active

**Comment by wmjordan** [comment]
> Here are the compiler errors

I am sorry that a file was missing in the commits.
Please update your clone with the latest one.
Hopefully you can compile the project and locate your problem.

**Comment by wmjordan** [comment]
@stecydube Could you try the 5540 build and see whether the exception reoccurs?

**Comment by wmjordan** [comment]
@stecydube 
Thank god. I was able to reproduce your issue on my machine and in less than 2 minutes I fixed the problem. It was caused by a premature attempt to alter the configuration persistence module.
Please download the latest beta which should work again.

**Comment by fitdev** [comment]
Using the latest beta. I was wondering if you can add an option to turn off the following:

- ALL custom syntax highlighting for non-*.cs files (razor, cshtml).
- Only non-CS syntax highlighting for non-*.cs files (razor, cshtml).

This way it may be possible to test how much Codist syntax highlighting is slowing down VS as I am experiencing issues with very slow typing and very slow recolorization with some of non-*.cs files.

**Comment by wmjordan** [comment]
@fitdev Thank you fo reporting your problem. I will try to make such an option in the beta version.

**Comment by fitdev** [comment]
Thanks for adding that option (now I am testing with Codist Syntax Highlighting turned off completely - and it looks so bad compared with Codist, so hopefully I will be able to return back to Codist highlighting soon once I see if there is no significant performance impact).

No, there are no background tasks during slow down. In fact, even if there were any, usually, in my case, they do not affect the responsiveness of the editor (because they run on a different thread). I actually enabled background code analysis for _active document only_ (as opposed to all open documents or entire solution). That really shortened and reduced all background tasks. So now all such tasks finish very quickly. Maybe you should try it yourself.

Unfortunately I can't go back to VS 2017 because I am using latest .Net Core previews that require most recent Preview version of VS.

**Comment by wmjordan** [comment]
VS 2019 16.7 preview 1 was just released.
According to the change log, it fixed an issue which caused VS to be extremely slow. Please try and see whether your problem is resolved.

https://developercommunity.visualstudio.com/content/problem/968845/visual-studio-2019-v1651-is-extrymly-slow.html

**Comment by fitdev** [comment]
Thank you for the tip. That's what I am using already, and it is still slow (not always but often, depending on the concrete document I am editing). In fact it has almost always been slow even in VS 2017. It's ok with small projects, but with 100s of files and 10s of projects it is kind of slow. I guess it will be that way until they rewrite it for .Net Core.

**Comment by wmjordan** [comment]
Could you provide an open source project (in github) in which you can experience the same slowdown? I could try to clone or download it and see whether I can reproduce the problem here.

**Comment by fitdev** [comment]
I will see if I can find something. Though, to be honest I am _not saying_ that Codist is playing a big role in the slowdown (I don't think so). It's just that at the moment I decided to explicitly test it by disabling Codist syntax highlighting to see how much of an improvement I would get. Haven't done proper test yet, so I will let you know soon.

**Comment by wmjordan** [comment]
Alright, thanks for taking time to test it.

**Comment by fitdev** [comment]
I have never used VS on a laptop let alone on the one running on battery. Though it does give you freedom to work in a park or somewhere nice. Personally I am so used to multi-monitor setup when working in VS, so I don't think I could be productive on a laptop.
