### ISSUE TITLE
Codist 5.10 Release Candidate

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#142]
Download:
[Codist 6259](https://github.com/wmjordan/Codist/files/6236593/Codist.zip)

[Codist 6252](https://github.com/wmjordan/Codist/files/6215618/Codist.zip)
[Codist 6244](https://github.com/wmjordan/Codist/files/6161827/Codist.zip)
[Codist 6238](https://github.com/wmjordan/Codist/files/6081647/Codist.zip)
[Codist 6233](https://github.com/wmjordan/Codist/files/6028854/Codist.zip)
[Codist 6221](https://github.com/wmjordan/Codist/files/6017688/Codist.zip)
[Codist 6210](https://github.com/wmjordan/Codist/files/6017080/Codist.zip)
[Codist 6200](https://github.com/wmjordan/Codist/files/6014257/Codist.zip)
[Codist 6188](https://github.com/wmjordan/Codist/files/6002521/Codist.zip)
[Codist 6184](https://github.com/wmjordan/Codist/files/6000037/Codist.zip)
[Codist 6175](https://github.com/wmjordan/Codist/files/5995389/Codist.zip)
[Codist 6164](https://github.com/wmjordan/Codist/files/5988201/Codist.zip)
[Codist 6155](https://github.com/wmjordan/Codist/files/5981417/Codist.zip)
[Codist 6139](https://github.com/wmjordan/Codist/files/5979270/Codist.zip)
[Codist 6133](https://github.com/wmjordan/Codist/files/5977691/Codist.zip)
[Codist 6127](https://github.com/wmjordan/Codist/files/5974798/Codist.zip)
[Codist 6125](https://github.com/wmjordan/Codist/files/5971618/Codist.zip)
[Codist 6122](https://github.com/wmjordan/Codist/files/5971220/Codist.zip)
[Codist 6118](https://github.com/wmjordan/Codist/files/5938388/Codist.zip)
[Codist 6115](https://github.com/wmjordan/Codist/files/5937970/Codist.zip)

- [x] General
   - [x] Added project names to symbol tool tip (b6139, b6238)
   - [x] Fixed symbol locations could popup in wrong document window (b6139)
   - [x] Displayed project name in tool tips for items in the source locations popup (#150, b6155)
   - [x] Fixed display build timestamp option was not saved (b6164)
   - [x] Improved working experience with keyboard (b6221)
- [x] Navigation Bar
   - [x] Displayed parent namespace nodes (#67, b6122, b6125, b6127, b6133, b6139, b6164, b6175, b6184, b6188, b6200, b6210, b6221)
   - [x] Fixed shortcut keys were disabled after switching tabs (#146)
   - [x] Fixed some errors about the Markdown title list (b6155)
   - [x] Added shortcut key to specify search scope in the root item menu (#149, b6155)
   - [x] Changed shortcut keys to avoid conflicts with VS 2019 (b6155)
   - [x] Changed the behavior of drop-down menus, closing them when any sub-item was clicked (b6210)
   - [x] Fixed VS crash (#154)
   - [x] Fixed broken Navigation Bar after split document window was merged (#135, b6259)
- [x] Scrollbar Marker
   - [x] Fixed Markdown title markers were not displayed if both NaviBar and Syntax Highlighting were disabled (b6155)
- [x] Smart Bar
   - [x] Supported 0x-prefixed hex numbers in Increment Number command (b6252)
   - [x] Removed space between CJK characters in the Join Selected Lines command (b6252)
   - [x] Removed slashes between lines when joining lines in C#, C/C++, Java/JavaScript files (b6252)
   - [x] Kept toolbar when executing Delete command (b6252)

The beta version includes the following enhancements and fixes in v5.9.1:

- [x] Highlight
    - [x] Added option to highlight constructors with the syntax styles of their container types (#141)
    - [x] Addressed indentation in attribute notations (#140)
    - [x] Fixed an error when special punctuation highlight was disabled (#143)
- [x] Navigation Bar
    - [x] Fixed a crash when both syntax highlight and scrollbar marker were disabled (#145)

**Comment by fantasyz** [comment]
![image](https://user-images.githubusercontent.com/3223242/108135131-845cc180-70f2-11eb-983b-2578d54cc135.png)

Found a bug.
The functions inside the macro #if #endif is missing from in the Navibar AND its members dropdown list. You can see that it directly showing the GetUnitColor() after the macro.

**Comment by wmjordan** [comment]
> The functions inside the macro #if #endif is missing from in the Navibar AND its members dropdown list

I could not reproduce this.
Please try to click somewhere else to refresh the NaviBar if it is out of sync.

**Comment by fantasyz** [comment]
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException


   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.BaseTypeDeclarationSyntax, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolCore(Microsoft.CodeAnalysis.SyntaxNode, System.Threading.CancellationToken)
   at Codist.CodeAnalysisHelper.GetSymbol(Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.SyntaxNode, System.Threading.CancellationToken)
   at Codist.SemanticContext+<GetSymbolAsync>d__47.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Codist.NaviBar.CSharpBar+NodeItem+<AddItemsAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Codist.NaviBar.CSharpBar+NodeItem+<CreateMenuForTypeSymbolNodeAsync>d__19.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Codist.NaviBar.CSharpBar+NodeItem+<HandleClick>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
