### ISSUE TITLE
Codist 5.12 Beta

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#164]
Download:
[Codist 6594](https://github.com/wmjordan/Codist/files/6860463/Codist.zip)

[Codist 6592](https://github.com/wmjordan/Codist/files/6847307/Codist.zip)
[Codist 6589](https://github.com/wmjordan/Codist/files/6831013/Codist.zip)
[Codist 6562](https://github.com/wmjordan/Codist/files/6800459/Codist.zip)
[Codist 6548](https://github.com/wmjordan/Codist/files/6790126/Codist.zip)
[Codist 6539](https://github.com/wmjordan/Codist/files/6752756/Codist.zip)
[Codist 6536](https://github.com/wmjordan/Codist/files/6752013/Codist.zip)
[Codist 6522](https://github.com/wmjordan/Codist/files/6745232/Codist.zip)
[Codist 6505](https://github.com/wmjordan/Codist/files/6737422/Codist.zip)
[Codist 6501](https://github.com/wmjordan/Codist/files/6707484/Codist.zip)
[Codist 6489](https://github.com/wmjordan/Codist/files/6679769/Codist.zip)
[Codist 6485](https://github.com/wmjordan/Codist/files/6659774/Codist.zip)
[Codist 6477](https://github.com/wmjordan/Codist/files/6653488/Codist.zip)
[Codist 6470](https://github.com/wmjordan/Codist/files/6641410/Codist.zip)
[Codist 6451](https://github.com/wmjordan/Codist/files/6597761/Codist.zip)
[Codist 6436](https://github.com/wmjordan/Codist/files/6573118/Codist.zip)
[Codist 6426](https://github.com/wmjordan/Codist/files/6564734/Codist.zip)

## General
- [x] Fixed potential crash when opening renamed code file (b6426)
- [x] Fixed incorrect results for Find Referrers command (b6477, #160)
- [x] Addressed potential crashes when updating syntax model (b6489, #167)
- [x] Fixed a crash when event argument type was unknown (b6539)
- [x] Fixed VSIX version incrementation could cause error when building projects (b6548)

## Syntax Highlight
- [x] Syntax highlight might block the user interface significantly (b6436, b6451, b6477, b6485, b6489, b6505, b6522, b6538, b6548, b6562, b6589, #165)
- [x] Supported highlighting ImplicitArrayCreationExpression (b6539)

## Navigation Bar
- [x] Fixed incorrect selection when selecting code from partial types in NaviBar members list (b6426)
- [x] Fixed a crash (b6592, b6594)

## Super Quick Info
- [x] Fixed C# keywords, string were not using customized color in Super Quick Info (b6426, b6470, #166)
- [x] Made C# Quick Info displaying and analyzing property accessors (b6426)
- [x] Improved numeric forms (b6589)
       ![image](https://user-images.githubusercontent.com/12182730/125957808-212b2f17-447b-4818-b877-b8a868351d4e.png)

**Comment by fitdev** [comment]
BTW I have tried VS 2022 Preview 1.1. It seems to perform better than VS 2019. I managed to get Codist half-working in there (Syntax Highlight and Navi Bar work), but Super QuickInfo does not work. Hopefully you can make an official VS 2022 release soon.

**Comment by fitdev** [comment]
Also, I am 95% certain that Codist 6501 or earlier version introduced a serious memory leak into VS. At first I was not sure when I was using VS 2019 (because in there I had many documents open), but I did see there memory raise to ~3GB, GC going crazy and everything grinding to a halt after using it for about an hour (with just a few documents editing). But then I saw the same behavior on VS 2022 with memory going to 9GB after editing a few docuemnts and having just a few documents open. When I disable Codist, I do not experience this issue in either 2019 or 2022.

**Comment by wmjordan** [comment]
@fitdev thank you for reporting this.
I will look into the memory leak issue.

**Comment by fitdev** [comment]
I think memory leak started to happen with late May / early June builds 6391-6426, and definitely by build 6489.

**Comment by wmjordan** [comment]
The leakage has not yet been fixed--I guess. But the performance should be better.

**Comment by wmjordan** [comment]
> Super QuickInfo does not work

There is no supprise to see that.
The Super Quick Info hacks the WPF user interface. It won't work if the WPF structure of the Quick Info in VS 2022 is changed.
That kind of thing happened before when a certain sub versions of VS 2017 or VS 2019 were released.

**Comment by wmjordan** [comment]
The beta 6522 has addressed both memory leak and performance issues.

**Comment by fitdev** [comment]
Awesome! Will check it out! Thanks for the quick fix. So what was causing the leak (I never got around to inspecting devenv.exe process's heap)?

**Comment by wmjordan** [comment]
Redundant event hooks caused CPU crazy and memory leak.

**Comment by fitdev** [comment]
Oh I see. I am giving it a try. Will let you know in a few days once I got a chance to test it thoroughly. Thanks a lot for your work!

**Comment by wmjordan** [comment]
Thank you for your test. You help a lot.

**Comment by fitdev** [comment]
Got a VS crash when I clicked on one of the dropdown items on the NaviBar (the very 1st button - to the left of the Home button):

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at Codist.CodeAnalysisHelper.GoToSource(Microsoft.CodeAnalysis.Location)
   at Codist.Controls.SymbolItem.GoToSource()
   at Codist.NaviBar.CSharpBar.MenuItemSelect(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```

**Comment by wmjordan** [comment]
That's really weird. It seems to be the same as #163.
Could you reproduce this issue and see what file is supposed to be opened?

**Comment by fitdev** [comment]
No _new_ file was supposed to be opened. The type in its entirety was already defined in the currently active document tab. All that should have happened is the current document should have scrolled to the start of the definition of the type I clicked on, in _the same document_. But instead it crashed VS with that exception.

**Comment by wmjordan** [comment]
Could you take the trouble making a sample project which reproduces this problem?

**Comment by fitdev** [comment]
Sorry to cause confusion, upon further testing I discovered that this happens only in VS 2022, VS 2019 there are no crashes, but VS 2022 _always_ crashes regardless of the files involved. Sorry for the confusion, as I know that you do not yet officially support VS 2022.

**Comment by wmjordan** [comment]
Alright then, thanks for the feedback.

**Comment by wmjordan** [comment]
> In b6539 I got a VS crash when I clicked on one of the dropdown items on the NaviBar

There's a new beta which might fix your problem on VS 2022. Please give it a try.

**Comment by fitdev** [comment]
Thank you for the new version. I will let you know how it goes later today. As an aside, the biggest missing feature for me in VS 2022 is that Super QuickInfo does not really work at all (miss those detailed tooltips and evaluated constant values).

**Comment by wmjordan** [comment]
Darn, some method must have been removed from VS 2022 thus it no longer worked.
