### ISSUE TITLE
Codist 6.3 Beta

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#197]
## Download
[Codist 7295](https://github.com/wmjordan/Codist/files/8819989/Codist.zip)

[Codist 7289](https://github.com/wmjordan/Codist/files/8792556/Codist.zip)
[Codist 7276](https://github.com/wmjordan/Codist/files/8769599/Codist.zip)
[Codist 7268](https://github.com/wmjordan/Codist/files/8752445/Codist.zip)
[Codist 7260](https://github.com/wmjordan/Codist/files/8737787/Codist.zip)
[Codist 7254](https://github.com/wmjordan/Codist/files/8737258/Codist.zip)
[Codist 7251](https://github.com/wmjordan/Codist/files/8696864/Codist.zip)
[Codist 7241](https://github.com/wmjordan/Codist/files/8692690/Codist.zip)
[Codist 7233](https://github.com/wmjordan/Codist/files/8667769/Codist.zip)
[Codist 7230](https://github.com/wmjordan/Codist/files/8646214/Codist.zip)
[Codist 7193](https://github.com/wmjordan/Codist/files/8530704/Codist.zip)

## What's new
- General (🆕)
   - [x] Added new options to hide VS UI elements (7289)
      <img width="692" alt="image" src="https://user-images.githubusercontent.com/12182730/170850067-ea41c526-898a-4258-bba0-9176f39f9532.png">
   - [x] Added Web Search command for symbols in NaviBar and Quick Info right click menus
- Jump List (🆕)
   - [x] New option to add shortcuts to Jump List of VS in Start Menu
      <img width="330" alt="image" src="https://user-images.githubusercontent.com/12182730/167278936-040ed73a-e423-4f28-9472-7e6cce730074.png">
- NaviBar
   - [x] Fixed a bug that could crash VS when Delegate node was clicked on C# NaviBar (7193)
   - [x] Fixed a bug that caused incorrect titles in Markdown documents (7233, 7248, #178)
- Scrollbar Marker
   - [x] Fixed compiler directives were not displayed on Scrollbar Marker (7230)
   - [x] Fixed a bug which caused incorrect comment marker were displayed (7233)
- Smart Bar
   - [x] Enabled multiline edit all matching command in SmartBar (7230)
   - [x] Added "View URL in Browser" command (7268)
- Auto Build Version
   - [x] Changed behavior to change version only when files in a project was modified within VS (7230)
- Advanced Syntax Highlight
   - [ ] Fixed a bug which caused breakpoint background to be an undesirable one (7251, 7254, 7260， #199)
   - [x] Fixed a bug in customization window that crashed VS (7268)
   - [x] Fixed a bug that syntax highlight was not fully applied after solution restoration or file changes (7276, #188)

**Comment by wmjordan** [comment]
A new beta version is released with a new feature to add shortcuts to launch VS in various modes.

The behavior of Auto Build Version is also changed to rewrite version numbers for projects only when their files were modified within VS. For instance, the projects referenced by a unit test project would all get recompiled even if you just made modification to unit test cases, since the Auto Build Version will change the project numbers all the way. From this version on, the modification to code files with VS are monitored and Auto Build Version won't change other projects' version numbers unless you modify code files within them. So, a lot of unnecessary rebuilds are prevented.

**Comment by wmjordan** [comment]
Hi, @fitdev

My friend.
A bug that caused the background color of statements with breakpoint set to gray was discovered recently.
The latest version has made some modification to provide a workaround for that bug.
Could you help test this version and see whether it works on your side?

**Comment by fitdev** [comment]
@wmjordan Yes, I noticed that, though did not realize it was Codist. Was not a big deal for me so I never bothered to investigate.

I will test it soon and let you know. In the meantime, I noticed that a static method group is does not use style for static members (underline in my case)...

![2022-05-20 16_23_05-Syntax Highlight Configurations](https://user-images.githubusercontent.com/8166847/169537560-040d8031-c769-4e20-963c-a1efdb9e5503.jpg)

The highlighted symbol should have underline style applied, but it does not. Is this a bug? (In the hierarchy of styles on the screenshot _only static_ symbols/members have underline style set, all other items do not affect/change underline style, so it should persist).

**Comment by wmjordan** [comment]
That's weird.
I never experience that problem.
Have you explicitly set the `Underline` style of `C#: Method`?

**Comment by fitdev** [comment]
No, not of any C# method. Only _static_ members have underline explicitly set. Instance methods are not to be underlined.

[Config.json.zip](https://github.com/wmjordan/Codist/files/8747217/Config.json.zip)

**Comment by fitdev** [comment]
I can also confirm that the latest version have fixed the breakpoint color issue. Great job!

**Comment by fitdev** [comment]
Oh, and just realized that the same issue is with _extension methods_, they should be underlined but are not:
![2022-05-21 11_07_53-Syntax Highlight Configurations](https://user-images.githubusercontent.com/8166847/169642427-63b39106-d4f7-4975-8b02-0713fb447524.jpg)

**Comment by fitdev** [comment]
And one last thing, if it matters, I am using `Visual Studio 2017` _Editor Color Scheme_ (as opposed to the new default color scheme introduced with VS 2019).

**Comment by wmjordan** [comment]
I changed the color scheme to VS 2017 and imported your config file.
The underlines were working as expected on my machine.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/12182730/169643430-58a75edd-172e-4696-8924-bfe6deb923ec.png">

**Comment by fitdev** [comment]
Thank you for looking into this. Strange. Perhaps it has something to do with my _user code_ setting - it uses Bold version of _Fira Code_ font, while non-user code uses regular _Fira Code_? Also I am on latest VS Preview - 17.3 Preview 1.

I remember it worked fine before, but cannot recall when it stopped displaying underline.

**Comment by wmjordan** [comment]
There are quite a few history versions of Codist here.
Could you take the trouble try installing them and see whether there is any version works for you?

**Comment by fitdev** [comment]
Well, it was that way already with the version published in VS Gallery, i.e. 7176. So it's not recent change that caused this.

**Comment by wmjordan** [comment]
That's weird.
Do you have any other syntax highlight related extensions?

**Comment by fitdev** [comment]
No, I don't. Also the issue exists with all kinds of projects - Net Core and Net Framework. Also I noticed that sometimes the selected code highlight analysis would have duplicate entries:

![2022-05-22 13_17_42-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/169690658-4d92842a-fbde-48db-a55c-ae9901b00ab6.jpg)

**Comment by wmjordan** [comment]
> Also I noticed that sometimes the selected code highlight analysis would have duplicate entries

If it is duplicated, it is duplicated.
You can press down the Ctrl key while you hover your mouse cursor onto the item and temporarily disables the Super Quick Info, revealing the original Quick Info items.

**Comment by wmjordan** [comment]
> I noticed that sometimes the selected code highlight analysis would have duplicate entries

It might not be the cause of the problem.
The duplicated method names also occur on my machine.
Yet the display is fine here.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/12182730/169727214-ee59e1c8-944d-4269-9446-a61a7120d8f0.png">

**Comment by wmjordan** [comment]
Since your configuration has assigned underline to the `static symbol`, could you try disabling Codist and see whether the static methods can be underlined?

**Comment by wmjordan** [comment]
It is weird that there are two `IClassicationType` instances that do not reference equals each other but having the same `Classification` property (i.e. _static symbol_ and _method name_).

Since your configuration has assigned underline to the `static symbol`, could you try disabling Codist and see whether the static methods can be underlined?

**Comment by fitdev** [comment]
> Since your configuration has assigned underline to the static symbol, could you try disabling Codist and see whether the static methods can be underlined?

What do you mean? Without Codist, how can they be underlined? As far as I know there is no built-in VS mechanism to allow underline decoration at all, let alone one that applies to static symbols.

BTW. As an experiment I did try to change statics and extension methods styles in Codist to use different background colors, and it _does work_, so they are all correctly identified. It's just that underline style is not applied to them for some reason. I could use your new _Line_ style but the problem with it is that it does not reuse the text's color.

**Comment by fitdev** [comment]
Also, I noticed that even on other kinds of symbols underline does not work. It is as if this style is simply ignored by VS.

**Comment by wmjordan** [comment]
> What do you mean? Without Codist, how can they be underlined?

Oops, My mistake. No, they can't be underlined.

> your new _Line_ style but the problem with it is that it does not reuse the text's color

It is really a problem. There's no way to reuse the text color as far as I know.

**Comment by fitdev** [comment]
Well, don't look too hard into this as apparently it is happening only on my end. Maybe a future VS update will fix it. If something comes to your mind, let me know.

BTW I have double checked all extensions - and I have nothing other than Codist which changes text editor styles.

**Comment by fitdev** [comment]
Actually I also noticed that despite having _Underline reassigned variables_ option under C# settings, reassigned variables are not underlined. Apparently for some reason my VS Editor just does not show underline font style. So I do not think it has anything to do with Codist, most likely some weird config issue with my VS.

**Comment by wmjordan** [comment]
Hmm, thank you for sharing your findings.
I will dig into the syntax highlight part later when I have time. It is really a mysterious black box.

**Comment by wmjordan** [comment]
Hmm, thank you for sharing your findings.
I will dig into the syntax highlight part later when I have time. It is really a mysterious black box.

**Comment by fitdev** [comment]
I have found the problem to be related to me updating my [Fira Code](https://github.com/tonsky/FiraCode) font to the latest version a few months back. Afterwards no underlines anywhere.

However, I have also set these: 
![2022-05-23 10_25_35-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/169765999-65af2da1-f5b0-4e5e-acc7-40427b90c5bf.jpg)
However when I try to change font, VS crashes with:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.Options.SyntaxHighlightCustomizationWindow+FontButton.SetFont(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

So right now I cannot experiment with these to see if changing to a different font here will restore underlines. If I change my font in VS Options to a different one, underlines _are restored_, but not everywhere - user code remains on `Fira Code` as per Codist's settings.

**Comment by wmjordan** [comment]
Yes, I noticed that while I was testing your configuration yesterday and I fixed it then.
Please try the new beta.

**Comment by fitdev** [comment]
Thank you! That indeed fixed the crash. But now I notice that there is just one `Fira Code` font in the list (without the variants like Light, Medium, etc.). VS Options display _all variants_ in the Font dropdown list. Could you please make it so that all font variants are explicitly listed in Codist's font dropdown list as well?

**Comment by fitdev** [comment]
BTW I have just found the issue. It was caused by _Text Sharp_'s extension _text formatting_ property value being set to `Display` instead of `Ideal`. Writing this here in case it helps somebody. So, sorry for all the trouble with underline style.

**Comment by wmjordan** [comment]
It may not be so easy. The list is returned from `System.Windows.Media.Fonts.SystemFontFamilies`.

**Comment by fitdev** [comment]
> It may not be so easy. The list is returned from System.Windows.Media.Fonts.SystemFontFamilies.

Hmmm. But it certainly used to work before somehow, because otherwise I could not have chosen font variants. But perhaps, when I did this the actual font files were a bit different and were installed as distinct fonts. Anyways, this is not a big deal, as I managed to revert back to the settings that work by manually editing json config file.

> And MacType is a recommended application for font rendition enhancements on Windows system, which have been with my computers for more than 10 years (including its ancestors).

Thank you for pointing this out! I will give it a try.

**Comment by wmjordan** [comment]
> it certainly used to work before somehow, because otherwise I could not have chosen font variants

Yes, it was. You reminded me. On my computer, there are hundreds of fonts installed. It was very slow to populate the drop-down. Thus I changed it to display font-families only.

**Comment by fitdev** [comment]
Oh I see. Well, maybe you can put a setting somewhere to let users see the whole list if they need to. That way most users will likely use the fast version, but some will use slower version. Or, perhaps you can cache the results, so that only the first time it is slow. I think font variants may be valuable when you want to preserve overall style in the editor, yet still allow for differentiation.

**Comment by wmjordan** [comment]
> Oh I see. Well, maybe you can put a setting somewhere to let users see the whole list if they need to. That way most users will likely use the fast version, but some will use slower version. Or, perhaps you can cache the results, so that only the first time it is slow. I think font variants may be valuable when you want to preserve overall style in the editor, yet still allow for differentiation.

Since the _Stretch_ option currently requires the font physically contains such a variant to work, it is useless to provide that option if the font does not have any variant for stretch. I can replace the current _Stretch_ option in the customization window with a _Variants_ drop-down.
Therefore, the dialog won't get more complex and the functionality just gets improved.

**Comment by fitdev** [comment]
> Since the Stretch option currently requires the font physically contains such a variant to work, it is useless to provide that option if the font does not have any variant for stretch. I can replace the current Stretch option in the customization window with a Variants drop-down.

I think that's a great idea!

> The above configuration works in the current version since it does not require a font is specified in Y. However, after the planned upgrade, the variant won't show up since the font is not explicitly specified in Style Y.

Yes, this is tricky. But for the time being you may require users to _always_ select a font in order for them to be able to select a variant. It kind of makes sense because different fonts may not have the same variants all the time, and so users should explicitly specify these.

**Comment by fitdev** [comment]
I noticed that sometimes I have persistent improper highlights in all of the opened tabs of _the same _project_. This is usually fixed by closing and reopening the document (merely typing does not work). Apparently these get out of sync after some refactoring or introduction of new members.

Correct:
![2022-06-02 09_00_54-Syntax Highlight Configurations](https://user-images.githubusercontent.com/8166847/171563878-7905d2a9-97ef-4315-8028-e8b3a49917dd.jpg)

Wrong:
![2022-06-02 09_02_08-Syntax Highlight Configurations](https://user-images.githubusercontent.com/8166847/171563930-192a98cb-19c6-41ce-b03f-0aacab9468a7.jpg)

To be honest I am not sure if this is a Codist issue, because VS's Highlighted Reference feature does not work either in the problematic document until it is reopened. So likely something gets wrong with the document state that causes VS to treat most of the parts as plain text or something. Still I thought I would mention it here.

**Comment by wmjordan** [comment]
I have not experienced such kind of issue that could not be fixed after typing something.

If the VS highlight did not work either, Codist would not work.

**Comment by fitdev** [comment]
Well, it may be something specific to the current preview version of VS or something. But I reported this just in case...

**Comment by wmjordan** [comment]
It is how the Quick Info work.
I also found that sometimes it did not appear at the right position for me.
I tried to control where it appeared previously. However, I failed to find a way to precisely position it.

Shall I hack into its WPF properties again?

**Comment by fitdev** [comment]
Oh, I didn't realize it's VS's behavior. I thought it's to do with Codist. It's not that important for me. I can live with the current situation :)

**Comment by wmjordan** [comment]
Well, I am releasing the version 6.3 today.
