### ISSUE TITLE
Codist Beta 7.1

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#242]
# Download
[Codist 8135](https://github.com/wmjordan/Codist/files/10721154/Codist.zip)

[Codist 8132](https://github.com/wmjordan/Codist/files/10715366/Codist.zip)
[Codist 8114](https://github.com/wmjordan/Codist/files/10704986/Codist.zip)
[Codist 8106](https://github.com/wmjordan/Codist/files/10698041/Codist.zip)
[Codist 8102](https://github.com/wmjordan/Codist/files/10695001/Codist.zip)
[Codist 8085](https://github.com/wmjordan/Codist/files/10674977/Codist.zip)
[Codist 8078](https://github.com/wmjordan/Codist/files/10611018/Codist.zip)
[Codist 8068](https://github.com/wmjordan/Codist/files/10608669/Codist.zip)
[Codist 8048](https://github.com/wmjordan/Codist/files/10541703/Codist.zip)
[Codist 8046](https://github.com/wmjordan/Codist/files/10529482/Codist.zip)
[Codist 8038](https://github.com/wmjordan/Codist/files/10527367/Codist.zip)

# What's New
- Quick Info
   - [x] Fixed incorrect display XML Doc of C# property accessors
   - [x] Displayed C# property value XML Doc (#240)
   - [x] Added Shift to suppress Quick Info, if CtrlQuickInfo option was disabled
   - [x] Fixed some C# Quick Info was not coordinate with the builtin one
   - [x] Fixed incorrect C# Quick Info when hovering an expression keyword as a parameter
   - [x] Prevented huge field initializer from freezing VS
   - [x] Used editor font for enum values, numeric forms in C# Quick Info
   - [x] Supported C# 11 (#203)
   - [x] Added link to open corresponding assembly file from the symbol location info
   - [x] Fixed overridden struct methods were not using inherited documentations
- Smart Bar
   - [x] Displayed directory name instead of file name for the Open Folder command on Output Smart Bar
   - [x] Fixed incorrect selection after inserting URL from Markdown Smart Bar
   - [x] Moved "edit all matching" command from sub-menu to main Smart Bar
   - [x] Added Stage Selected Range and Revert Selected Range commands to DIFF Smart Bar
- Refactoring
   - [x] Fixed incorrect indentation of wrap with #region refactoring command
   - [x] Added interpolate string refactoring
   - [x] Added swap conditional expression results refactoring
   - [x] Added support ConditionalToIfRefactoring for VariableDeclarationSyntax
   - [x] Added SealClassRefactoring and ChangeAccessibilityRefactoring
   - [x] Kept whitespace after last expression in ConcatToInterpolatedStringRefactoring
   - [x] Removed unnecessary encompassing parentheses after ConcatToInterpolatedStringRefactoring
   - [x] Added WrapInTextRefactoring and InlineVariableRefactoring
- Navigation Bar
   - [x] Fixed incorrect positioning of C# NaviBar drop-down menu on VS 2017
   - [x] Fixed potential crash caused by namespace nodes on C# NaviBar (#241)
   - [x] Prevented huge field initializer from freezing VS
   - [x] Changed to use individual icons for explicit and implicit conversion operators
- Code Analysis
   - [x] Fixed duplicated entry in some commands when code files were multi-referenced in several projects
- Syntax Highlight
   - [x] Syntax highlight was not activated when the first opened document was Markdown, unless a code file was opened
   - [x] Added filter box in the highlight style customization window (#243)
   - [x] Used editor font when specified font did not exist
   - [x] Better supported font variations (#195)
       <img width="410" alt="image" src="https://user-images.githubusercontent.com/12182730/218035413-26ad331d-fe34-4764-896e-0b31417fe65c.png">
   - [x] Fixed syntax highlight settings were not fully applied after upgrading Codist (#227)
- Symbol Tool Tip
   - [x] Full path of assembly file was displayed (#230)
   - [x] Displayed attribute type documentation for constructors in symbol tool tip
- Extension Developer
   - [x] Displayed view roles in the document content type command

**Comment by fitdev** [comment]
Small suggestion: it would be great if the super quick info will also show the inheritance path of interfaces for a member that implements it:

![Screenshot_20230129_150412](https://user-images.githubusercontent.com/8166847/215324987-afe54646-2e5c-4cc6-9943-bb366cef20c8.png)

... similar to how it already does it when it lists interfaces implemented by a type:

![Screenshot_20230129_150347](https://user-images.githubusercontent.com/8166847/215325038-d1986ad5-c9e6-4432-a0a0-21f6273dfbf3.png)

**Comment by fitdev** [comment]
Another small issue: In various find members / types / implementations commands, sometimes there may be duplicates, when the same symbol is accessible _through more than one loaded project_:

![Screenshot_20230129_154918](https://user-images.githubusercontent.com/8166847/215327317-83edf690-22b5-49a3-9233-0b61557aff26.png)

So, perhaps there can be a simple way to exclude such duplicates by checking against file's path (whether we already have identically named symbol from the same file in the list)?

**Comment by wmjordan** [comment]
> In various find members / types / implementations commands, sometimes there may be duplicates, when the same symbol is accessible _through more than one loaded project_ (when the same file is directly included in several projects)

That's weird.
I have similar projects, but that thing have not happened after a fix.
Could you produce a sample solution for me to test?

**Comment by fitdev** [comment]
> I have similar projects, but that thing have not happened after a fix.

I should have clarified: it happens when the files are directly included in 2 or more projects, i.e. using `<Compile Include="SharedFiles\*.cs"...` in csproj (_not using shared projects_).

**Comment by wmjordan** [comment]
Thank you for making the demo.
I saw that.
The problem is that the `ClassShared` comes from in both projects.
However, it is not duplicated in the drop down on the Navi Bar.
<img width="356" alt="image" src="https://user-images.githubusercontent.com/12182730/215427795-891747d1-ff8d-41c3-a8ef-0e77790ffe1f.png">

I will see if it is possible to merge them together.

**Comment by wmjordan** [comment]
I seemed to have work this out.
Did this also occur on the Find Members command? How to reproduce it?

**Comment by fitdev** [comment]
> Did this also occur on the Find Members command? How to reproduce it?

I did not notice that.
If it is hard to fix, do not worry too much about this. It is a rather rare case.

**Comment by wmjordan** [comment]
Please test the new beta.

**Comment by fitdev** [comment]
In  8085 SUperQuick Info seems to be broken on enums - does not get displayed at all.

**Comment by wmjordan** [comment]
> In 8085 SUperQuick Info seems to be broken on enums - does not get displayed at all.

It does not seem broken on my computer.

I spell checked the source code and fixed some typos, perhaps it caused some settings were reset to default.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/12182730/217685652-bd7a0625-e227-404b-9a3c-ca1a81241b73.png">
<img width="238" alt="image" src="https://user-images.githubusercontent.com/12182730/217685693-7e8cd977-cf07-4c1c-b5b2-5fddf6da92c3.png">

**Comment by wmjordan** [comment]
Anyway, please try the new beta which has added a filter box in the Syntax Style Customization Window and a InlineVariableRefactoring to the Smart Bar.

**Comment by fitdev** [comment]
Thank you for the new beta. Still enum superquick infos __do not show at all__. All the other superquick infos work just fine. They worked in 8046, but after I jumped to 8085 they stopped working. I have not installed any other extensions or upgraded VS between then. So perhaps there is some change introduced between 8046 and 8085 that broke something. Not sure why it would work on your machine though.

**Comment by wmjordan** [comment]
Please upload your config file here and let me test it.

**Comment by fitdev** [comment]
Here it is.

[Config.json.zip](https://github.com/wmjordan/Codist/files/10694390/Config.json.zip)

**Comment by fitdev** [comment]
I just realized that it's not just enums - it's all _constants_! There is no super quick info on any constant!

**Comment by wmjordan** [comment]
For numeric forms, you have to check the _Numeric forms_ option in the C# Quick Info options page.
For string length, hash code, check the _String length, hash and content_.

**Comment by fitdev** [comment]
I have it all checked already:

![Screenshot_20230209_103535](https://user-images.githubusercontent.com/8166847/217747396-9db2ab1a-1ba1-4f83-9cf4-774e592598ac.png)

Plus, wouldn't VS's default tooltip appear even if I did not have these options checked? Right now _nothing_ appears when I hover over constants.

**Comment by wmjordan** [comment]
Sorry. I managed to reproduce your problem. I am working on it.

**Comment by wmjordan** [comment]
It seems that it has something to do with a recent commit which attempts to use editor font to display numeric constant values. On my computer with your config, a font just does not exist and the code will fail. Please try the new beta which has addressed the font problem and see whether the problem is fixed.

**Comment by fitdev** [comment]
But now I just noticed a different issue - the distinction between user and non-user code is gone in the editor. All code now appears as if it was _not_ a user code, even though I have a different font set for user code.

**Comment by wmjordan** [comment]
> But now I just noticed a different issue - the distinction between user and non-user code is gone in the editor. All code now appears as if it was _not_ a user code, even though I have a different font set for user code.
> 
> I think it has to do with this new version somehow losing the font _variant_. I use Fira Code Light for regular code and Fira Code Medium for user code which makes it bolder. But these 2 variants do not appear in the font list dropdown. So somehow Codist's latest version interpreted both variants as just the same font. So the issue is with the variants of the same font support (if I change the font to something entirely different user code is highlighted properly).

Hmm, perhaps it is the reason, as stated in #195 .

**Comment by fitdev** [comment]
But it worked great in 8085, so what has changed? I don;t mind not being able to specify the font variant in the drop-down, but I really, really would like it to work if it is specified in the config file manually.

**Comment by wmjordan** [comment]
It seems that the font handling in WPF is more complicated than what I thought.

The font creation procedure seems to have parsed the name and located the typeface "Fira Code", then looked for the "Light" or "Medium" variant. I will investigate it later.

**Comment by fitdev** [comment]
Is it safe for me now to revert back to 8046 by uninstalling Codist first and then installing older version?

**Comment by wmjordan** [comment]
Yes.

**Comment by wmjordan** [comment]
Does the typeface name "Fira Code" appear on the customization window?

I will work on #195 when I have time later so you don't have to manually set the font name.

**Comment by fitdev** [comment]
Yes - all variants are there:

![Screenshot_20230209_125240](https://user-images.githubusercontent.com/8166847/217778768-95ba567e-7511-4d59-8dc7-4e0a6eb0852d.png)

**Comment by fitdev** [comment]
> Does the typeface name "Fira Code" appear on the customization window?

Oh, you meant in Codist? Here it is - just 2 versions:

![Screenshot_20230209_125725](https://user-images.githubusercontent.com/8166847/217780031-f4aac451-739b-485b-ac37-f2c2d599dd49.png)

**Comment by fitdev** [comment]
Just to let you know: I downgraded to 8046, which was working fine before (I.e. super quick infos were displayed for constants and user code was highlighted), but now, for some reason super quick infos for constants do not appear just as they did not appear in 8085, but the user code highlighting with Fira Code Medium works fine. Why, all of a sudden there are no tooltips on constants in 8046 which was working before I have no idea, but at least I have user code highlighting back which is probably more important for me.

So, then to summarize: the latest beta 8102 fixed the super quick info display on constants, but introduced an issue with font variants, whereas _any previous beta_ that I tried in this batch, 8046 - 8085, - they support font variants (such that user code is properly highlighted), but they all have the super quick info for constants not working.

**Comment by fitdev** [comment]
One more small thing, I did mention this before and you said it is rather difficult to do, but I find it very annoying - the way VS positions super quick infos often leads to it being displayed _above_ the cursor, so you cannot click on the needed line / character because super quick info tooltip which just appeared is blocking the view. Perhaps there is an easy hack you can enable whereby the tooltip is simply _always_ offset say by 40 pixels down and right?

**Comment by wmjordan** [comment]
> for a long time after I install new version of Codist, VS Editor Color Scheme gets reset to VS 2019 one (even though in the options it shows as VS 2017), so I almost always, after I upgrade Codist have to first open VS and go to options, and do the trick: VS 2017 color scheme -> VS 2019 -> VS 2017 back (my preference), then restart VS, only then everything would be properly colorized

It has something to do with #227.

@Decimation
Let's try the new beta which supports font variants now.

> Perhaps there is an easy hack you can enable whereby the tooltip is simply _always_ offset say by 40 pixels down and right?

NO. I am sorry. If the Quick Info is offset away from the cursor, when you move the cursor, the Quick Info just disappears! That is the way it works. I had also been badly bothered by the Quick Info that covered the cursor. No way out. For so many years!

**Comment by fitdev** [comment]
> NO. I am sorry. If the Quick Info is offset away from the cursor, when you move the cursor, the Quick Info just disappears! That is the way it works. I had also been badly bothered by the Quick Info that covered the cursor. No way out. For so many years!

Oh I see. I hope they will fix it in VS soon then.

**Comment by fitdev** [comment]
Thank you so much! It works great! Now everything seems to be working - the font variants, and the super quick infos!

**Comment by wmjordan** [comment]
Thank you all participants!

I am going to release this version in the marketplace in a few days.
If you found any problem unmentioned before, please let me know.

**Comment by wmjordan** [comment]
@fitdev 
Please test the new beta, which might have successfully fixed #227.

**Comment by fitdev** [comment]
Thank you for the new beta. I will try it soon. However the thing is that this issue was _not happening every time_. I still have not figured out why some updates go smoothly, and others require me to change color scheme. So, even if it does work this time, there is no guarantee it was fixed. I will certainly let you know if I experience the color scheme issue at some point again after performing an upgrade.

**Comment by wmjordan** [comment]
> So, even if it does work this time, there is no guarantee it was fixed

It previously occurred on my machine most of the time (more than 50% possibility), after each upgrade.
However, before 8132, I manually made several versions (merely changing version number then recompile) and installed each of them, no more reoccurrence. Thus I put it here.

**Comment by fitdev** [comment]
I experienced similar behavior. So I will let you know if I experience color theme issues after upgrade.

**Comment by wmjordan** [comment]
There is a new beta. Small improvement for the inline variable refactoring.
