### ISSUE TITLE
Codist Beta 7.3

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#251]
## Download
[Codist 8534](https://github.com/wmjordan/Codist/files/11242091/Codist.zip)

[Codist 8524](https://github.com/wmjordan/Codist/files/11239069/Codist.zip)
[Codist 8514](https://github.com/wmjordan/Codist/files/11220152/Codist.zip)
[Codist 8501](https://github.com/wmjordan/Codist/files/11197449/Codist.zip)
[Codist 8495](https://github.com/wmjordan/Codist/files/11184732/Codist.zip)
[Codist 8493](https://github.com/wmjordan/Codist/files/11182457/Codist.zip)
[Codist 8484](https://github.com/wmjordan/Codist/files/11175942/Codist.zip)
[Codist 8477](https://github.com/wmjordan/Codist/files/11167889/Codist.zip)
[Codist 8466](https://github.com/wmjordan/Codist/files/11148587/Codist.zip)
[Codist 8461](https://github.com/wmjordan/Codist/files/11144520/Codist.zip)
[Codist 8448](https://github.com/wmjordan/Codist/files/11128777/Codist.zip)

## What's New
- General
  - [x] A new icon for Codist (with a Chinese character meaning "Code")
  - [x] Displayed C# Property parameter types in symbol tool tips and symbol menu
  - [x] Used specific icons for C# explicitly implemented interface members
- Super Quick Info
  - [x] Made signature name and value part of C# Quick Info selectable
  - [x] Used various icons for compiler error message (#37)
  - [x] Tweaked spacing of items (#244)
  - [x] Changed label for _Containing namespace and assembly_ option
  - [X] Displayed Quick Info for C# `await`
  - [x] Fixed broken text-only C# XML Doc Quick Info support
  - [x] Improved symbol resolving in C# Quick Info for parentheses
  - [x] Added more data flow analysis results for C# blocks
  - [x] Added options to show containing type for members and display code names in C# XML Doc with editor font
      <img width="518" alt="image" src="https://user-images.githubusercontent.com/12182730/230752271-bafae63d-6f29-4755-b658-bf7781c2aadf.png">
  - [x] Improved support for C# 11
  - [x] Improved support for brackets, LINQ, accessor declarations (part of #93)
- Syntax Highlight
  - [x] Used default text color if classification foreground color was not defined
  - [x] Fixed a bug caused memory leak and performance deterioration
  - [x] Fixed that underline and strikethrough style could not be properly removed
  - [x] Some syntax highlight styles were not properly rendered
  - [x] Improved highlight for indexers, accessor declarations, LINQ range variables
- Refactoring
  - [x] Fixed incorrect code produced by ConditionalToIfRefactoring
  - [x] Added a CommentToRegionRefactoring
  - [x] Fixed MultiLineListRefactoring was not working when expression was also an ArgumentSyntax
- Extension Developer
  - [x] Used an information-rich "Show Active Window Properties" dialog to replace the old Show Document ContentType properties dialog

**Comment by DimitarCC** [comment]
Thats cool. I can not test at the moment but looking into the code i understood that you identify the severity of the analyzers issue based on its text. Did i understood right?
Is that mean if you change the severity manually via 
 .editorconfig it will not detect it?

**Comment by wmjordan** [comment]
> I can not test at the moment but looking into the code i understood that you identify the severity of the analyzers issue based on its text.

Yes, you are right.
I could not find a way to get the warning severity from existing API.
If you know one, please tell me.

**Comment by wmjordan** [comment]
> @wmjordan
> 
> Yes i have a workaround solution....

I know about that workaround, years ago.

It has limitations. For instance, I usually hide warning and information items in the Error List, thus those items will not be available from the API of the Error List. And it can be slow, if the list is quite long.

Thus I don't want to take it.

**Comment by DimitarCC** [comment]
@wmjordan 

You are not right about some things....
First of all you can make it to get all information not matter what is displayed in the errorlist. I also hide warning and information but  that not prevent display in the tooltip.
Getting of errorlist entries is on event so it fill them up only when the error list changes. Yes maybe can be slow when there are several thousands of items. But i tried it with 400 items in the list and i dont see any slowdown. 

How do you think the Microsoft's extension Solution Error Visualizer works without slowdown? It uses the ErrorList for that.

But ofcource is your choice. :)

**Comment by wmjordan** [comment]
> How do you think the Microsoft's extension Solution Error Visualizer works without slowdown?

It was a story years ago. Solution Error Visualizer was hiding warnings or errors if corresponding filters were disabled while I was using that extension. I no longer used that extension after upgraded to VS 2019 or 2022--I could not remember. Perhaps things got changed in recent versions of VS.

Anyway, I found another way to deal with this problem without the Error List.

**Comment by DimitarCC** [comment]
@wmjordan 

What is that way? If you dont mind share it.

**Comment by wmjordan** [comment]
Codist is open-sourced.
The solution will be there if it passes my tests.

**Comment by DimitarCC** [comment]
OK. I wanted to know it earlier since i can use it in my other things i am developing, but anyway i will wait then.

**Comment by DimitarCC** [comment]
P.S. I hope your way will work even with external analyzers. ErrorList way works with them too ;)

**Comment by fitdev** [comment]
I noticed that recent versions of Codist reset the VS's bracket matching color to barely visible light gray. The fix is to go to VS Options, Fonts and Colors and to _change_ the current color of the bracket matching and bracket matching rectangle to a different color.

**Comment by wmjordan** [comment]
> Codist reset the VS's bracket matching color to barely visible light gray

I don't think Codist is resetting the brace matching color.
I reset the Experimental instance on my computer and disabled Codist. The default color was not vivid at all.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/12182730/229664634-fbd7e77d-d3a8-4bb1-a0ee-c649ac11f313.png">

**Comment by wmjordan** [comment]
> I hope your way will work even with external analyzers

Yes, it does.
<img width="196" alt="image" src="https://user-images.githubusercontent.com/12182730/229665517-b746ac13-6314-4bc6-8f9e-01dafcff4d7d.png">
<img width="239" alt="image" src="https://user-images.githubusercontent.com/12182730/229665596-0cc11491-e86f-40bf-9578-e9b4dee6832e.png">
<img width="212" alt="image" src="https://user-images.githubusercontent.com/12182730/229665772-2a1cf968-2ce9-4d19-bccc-7a29861211d2.png">
Treat warnings as errors:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/12182730/229666415-974d7dfa-0e4a-4462-bbf3-316801199d20.png">

**Comment by DimitarCC** [comment]
@wmjordan 

Cool. Generally it works. But have some issues...

For example:
![image](https://user-images.githubusercontent.com/1904901/229692354-d6d97100-f334-4899-a89f-d4f3eae9ee19.png)

it show IDE0002 as suggestion.

but it is actually hidden ;)

![image](https://user-images.githubusercontent.com/1904901/229692493-39e4f22f-6cc5-484a-a824-39e2036eea5e.png)

**Comment by fitdev** [comment]
> I don't think Codist is resetting the brace matching color.

Sorry about that. I think if I remember correctly you said a few months back that Codist might be doing this and you have fixed the issue, so I thought the issue has appeared again and assumed it to be Codist. I guess it is some kind of VS bug.

**Comment by DimitarCC** [comment]
@wmjordan 

About the "problem" above with not displaying correct severity....

There is a way to fix that.....

However it involve some reflection since the required properties are not public...

Well you didnt provide the code for your beta but i assume you use  IErrorTag to retrieve the info.

But IErrorTag provide publicly only the ErrorType which is different than the severity.

But you can get the severity from a private property that contains DiagnosticData.

in this way you get the correct severity.

![image](https://user-images.githubusercontent.com/1904901/229733074-1a70db12-744e-447f-8567-ca4452f25204.png)

**Comment by wmjordan** [comment]
@DimitarCC 
Thank you for your kind help.
Never mind.
The public property of `IErrorTag` should be sufficient.

**Comment by DimitarCC** [comment]
@wmjordan 

But it mistake the severity. If you want the severity  it is wrong. If you want to display type only is different story.

**Comment by wmjordan** [comment]
Don't be afraid.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/12182730/229737116-024dedb9-876a-4b29-aa96-1465ab3373ca.png">

**Comment by wmjordan** [comment]
Please try the new beta which has added more icon types for warning messages.

**Comment by DimitarCC** [comment]
Yes i have just tried it...
It works fine for the moment :)
Great work!

**Comment by DimitarCC** [comment]
@wmjordan 

OK they are some issues...

Sometimes when the diagnostics messages are first in the tooltip it not render icons at all.

**Comment by wmjordan** [comment]
> Sometimes when the diagnostics messages are first in the tooltip it not render icons at all.

Yes, I had met with this situation while I was working with my another project once.
I will try to fix it later when I encounter it once more.

**Comment by wmjordan** [comment]
@fitdev 
Have you tried the new C# Quick Info option that enables displaying containing types of a member?

**Comment by DimitarCC** [comment]
@wmjordan 

I have found something else...
About syntax highlighting for the entries that default have line defined it is not possible to remove the line not matter what you do.
For example if i want to remove the line from extension methods, i cant.

**Comment by wmjordan** [comment]
It is how VS's highlight works.
The extension method is not only an extension method, but ALSO a static member.
The static member has defined an underline.
So, if you want to remove the underline style, you not only need to undefine the underline in the extension method, but also the static member.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/12182730/230286775-04ab51c6-599b-4e06-a3c7-39497a491c30.png">

**Comment by fitdev** [comment]
> Have you tried the new C# Quick Info option that enables displaying containing types of a member?

Yes, it is really nice! Exactly what I was hoping for! Thank you for your work! The only suggestion is that it would be great if there was a way to visually distinguish some identifiers from regular xml doc text, because often for things like method names or property names, the font style is the same as regular text. Perhaps text editor's default font may be used for that?

**Comment by wmjordan** [comment]
> it is not possible to remove the line not matter what you do

@DimitarCC 
Please download the new beta version, which should have this problem fixed.

**Comment by wmjordan** [comment]
> visually distinguish some identifiers from regular xml doc text, because often for things like method names or property names, the font style is the same as regular text

@fitdev 
Hmm, I never expect this issue since I usually write my XML Doc majorly in Chinese, and member/type names in English, they distinguish each other quite well :) And I assign various colors for members, thus their colors differ against regular text.

**Comment by fitdev** [comment]
> Hmm, I never expect this issue since I usually write my XML Doc majorly in Chinese...

Yes, I agree, in your case they would look quite different and provide good contrast, but on in my case...

![Screenshot_20230406_140349](https://user-images.githubusercontent.com/8166847/230359267-338d4958-acb5-4ce1-b755-afc73ac92a73.png)

As you can see `EnableVisualStyles` and `SettingKeyForDSA` look practically indistinguishable from text. So, perhaps there should be an option to render all `<see cref="..." />`-based identifiers in monospace font (ideally the one set in Visual Studio). This way the other styles like colors and font styles would be preserved, but yet the identifiers themselves would be differentiated from the main text.

**Comment by wmjordan** [comment]
@fitdev 
I understand your request.
However, it is not so easy to elegantly change the typeface of the `<see/>` symbols at this moment.
I will try to see whether there's a better way to do so.

**Comment by wmjordan** [comment]
> Sometimes when the diagnostics messages are first in the tooltip it not render icons at all.

@DimitarCC 
This issue has been fixed in beta 8484.

**Comment by DimitarCC** [comment]
> > Sometimes when the diagnostics messages are first in the tooltip it not render icons at all.
> 
> @DimitarCC This issue has been fixed in beta 8484.

Well not really. It still doesnt work in some cases

![image](https://user-images.githubusercontent.com/1904901/230581855-e4f11170-0c55-4f64-a1e5-d1775e286775.png)

**Comment by DimitarCC** [comment]
> > it is not possible to remove the line not matter what you do
> 
> @DimitarCC Please download the new beta version, which should have this problem fixed.

Now i can remove underline but can not ever return it back. So i ended up with no underlines at all.
Is it a special way to do so?
If i check underline checkbox it shows line under but it not respond to line offset at all.

**Comment by wmjordan** [comment]
> Well not really. It still doesnt work in some cases

Sorry to see that. However, I could not find a way to reproduce this.



> If i check underline checkbox it shows line under but it not respond to line offset at all.

There's a logical mistake in the configuration window. I will fix it later.

**Comment by wmjordan** [comment]
> The error comes here

Yes, I have fixed that.
In beta 8484, the start index is always 0.
Are you using that version?

**Comment by DimitarCC** [comment]
I am using the lates code that you have committed before 9h (i have build it myself)
Is the code different than version 8484?

**Comment by wmjordan** [comment]
> I am using the latest code that you have committed before 9h (i have build it myself because i would like to change some icons you have used ;)) Is the code different than version 8484?

Yes.
The latest code might not be always in sync with the beta.

**Comment by DimitarCC** [comment]
aha. OK.

**Comment by wmjordan** [comment]
@fitdev 

I found a way to display the code symbols with the editor font in Quick Info.
Here's how it may appears.

<img width="352" alt="image" src="https://user-images.githubusercontent.com/12182730/230709810-d572b586-8fe4-4b68-b46c-9338970500b1.png">

Only the XML Doc part will use the code editor font.

**Comment by fitdev** [comment]
> Only the XML Doc part will use the code editor font.

That's great! Exactly what I was hoping for!

**Comment by wmjordan** [comment]
> > Only the XML Doc part will use the code editor font.
> 
> That's great! Exactly what I was hoping for!

@fitdev Please test the new beta.

**Comment by fitdev** [comment]
Works really well! Thank you so much for your work!

**Comment by wmjordan** [comment]
The previous beta versions could cause some errors while editing code files.
Please download the new beta.

**Comment by fitdev** [comment]
Using the latest beta and latest VS Preview 17.6 Preview 3, I got a crash when interacting with NaviBar:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.NaviBar.CSharpBar+NodeItem.<get_Symbol>b__16_0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.Threading.Tasks.Task>, Microsoft.VisualStudio.Threading.JoinableTask)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CompleteOnCurrentThread()
   at Codist.SyncHelper.RunSync[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.Threading.Tasks.Task`1<System.__Canon>>)
   at Codist.NaviBar.CSharpBar+NodeItem.get_Symbol()
   at Codist.NaviBar.CSharpBar+NodeItem.OnToolTipOpening(System.Windows.Controls.ToolTipEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.Controls.PopupControlService.ShowToolTip(System.Windows.DependencyObject, Boolean)
   at System.Windows.Controls.PopupControlService.PromotePendingToolTipToCurrent(TriggerAction)
   at System.Windows.Threading.DispatcherTimer.FireTick(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by wmjordan** [comment]
@fitdev 
Could you reproduce this issue and find out the particular code which causes this?

**Comment by fitdev** [comment]
It happened once only when I was either clicking on it to get a dropdown menu or when I started typing in the search field in the resx designer generated cs file.

**Comment by wmjordan** [comment]
@fitdev 
It should be a very rare case.
Please download the new beta and see whether the problem persists.

**Comment by wmjordan** [comment]
A new version is about to be publicly released.
Please help test this beta version.

**Comment by fitdev** [comment]
I noticed that the beta sometimes causes document syntax highlighting to revert to VS's default when typing in xml doc comments in the latest VS preview. Did not see it happen before.

**Comment by wmjordan** [comment]
> I noticed that the beta sometimes causes document syntax highlighting to momentarily (for a split-second) revert to VS's default when typing in the editor in the latest VS preview. Did not see it happen before.

Thank you for reporting this.
I managed to reproduce it.
Please try the new beta.

The new beta has also improved C# Quick Info to display info about LINQ expressions, and Super Syntax Highlight to highlight some brackets, operators and punctuations (part of #93).

**Comment by fitdev** [comment]
Thank you so much for a quick fix! So far it works a lot better and editor seems a lot more performant!

**Comment by wmjordan** [comment]
The new version was just released.
Thank you all my friends for your wonderful feedback!
