### ISSUE TITLE
Codist 7.4 Beta

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#254]
## Download
[Codist 8735](https://github.com/wmjordan/Codist/files/11483906/Codist.zip)

[Codist 8718](https://github.com/wmjordan/Codist/files/11464425/Codist.zip)
[Codist 8711](https://github.com/wmjordan/Codist/files/11449008/Codist.zip)
[Codist 8706](https://github.com/wmjordan/Codist/files/11443722/Codist.zip)
[Codist 8690](https://github.com/wmjordan/Codist/files/11427126/Codist.zip)
[Codist 8682](https://github.com/wmjordan/Codist/files/11402992/Codist.zip)
[Codist 8674](https://github.com/wmjordan/Codist/files/11380846/Codist.zip)
[Codist 8642](https://github.com/wmjordan/Codist/files/11341647/Codist.zip)
[Codist 8612](https://github.com/wmjordan/Codist/files/11328473/Codist.zip)
[Codist 8583](https://github.com/wmjordan/Codist/files/11294934/Codist.zip)
[Codist 8577](https://github.com/wmjordan/Codist/files/11292722/Codist.zip)
[Codist 8556](https://github.com/wmjordan/Codist/files/11269525/Codist.zip)

## What's New
- General
   - [x] Fixed the display of explicitly implemented indexer names on symbol list
   - [x] Fixed incorrect foreground brush in SymbolFormatter properties
   - [x] Added Open Output Folder commands to Build menu
      <img width="239" alt="image" src="https://user-images.githubusercontent.com/12182730/234454323-911a35f3-53e4-4d9c-bb85-e075ebe03a6b.png">
   - [x] Fixed potential deadlock in SymbolList
   - [x] Added a new option to display output window pane after build
   - [x] Displayed assembly directory for assembly symbol on symbol tool tip
   - [x] Improved performance of Color Quick Info, as well as predefined colors on symbol list
   - [x] Prevented Unload event handler from disabling symbol link after clicking on symbol list title
   - [x] Added tool tip to symbol analysis menu commands, unveiling hidden command options
   - [x] Allowed copying fully-qualified symbol name (#260)
- Super Quick Info
   - [x] Added a new option to display syntax node range related to the trigger point in C# code editor, so it might help you out of the sea of parentheses
      <img width="287" alt="image" src="https://user-images.githubusercontent.com/12182730/232986200-7db0d189-ecef-4163-becf-d07f0bbe7d61.png">
   - [x] Addressing an issue working with third party Quick Info extensions
   - [x] Fixed incorrect behavior of Super Quick Info (#255)
   - [x] Improved the display of C# explicitly implemented interface members
   - [x] Made namespace symbol on C# Quick Info interactive, displaying namespace and types when clicked (#257)
- Advanced Syntax Highlight
   - [x] Added squiggle underline style (#175)
      <img width="410" alt="image" src="https://user-images.githubusercontent.com/12182730/233633970-80bb82de-ab62-4f8f-9252-d0ec479ebbed.png">
   - [x] Added highlight style for C# local function declaration
      <img width="404" alt="image" src="https://user-images.githubusercontent.com/12182730/233633616-63aeb5b1-c934-4242-bc25-60088d64b8da.png">
   - [x] Fixed priorities of some syntax formats in syntax highlight
- Code Refactoring
   - [x] Fixed incorrect behavior of RemoveContainerRefactoring
- Scrollbar Margins
   - [x] Brought back line number and selection margin for text files
   - [x] Added total line number to LineNumberMargin
      <img width="419" alt="image" src="https://user-images.githubusercontent.com/12182730/234454766-c5fe74cc-94b5-4d76-aae7-81056758c40d.png">
   - [x] Corrected positioning of markers when scrollbar was in bar mode (shame to have this issue for so long) ^_^!!!
- Smart Bar
   - [x] Fixed `<see/>` button on C# Smart Bar was not working expectedly with type parameters defined in containing type
   - [x] Fixed C# Smart Bar was not working in Diff window
- Navigation Bar
   - [ ] Fixed Go To Definition could sometimes fail in member types on namespace lists 
- Extension Development
  - [x] Added more data to Show Active Window Properties command

**Comment by ChristopherHaws** [comment]
Hey there! Any chance we could get the beta versions uploaded to the [Open VSIX Gallery](https://www.vsixgallery.com)? It's a pretty common place for nightly/beta versions of VS extensions. To use it, you just need to [install the extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VSIXGallery-nightlybuilds) by Mads Kristensen.

Thanks for the great extension! :)

**Comment by DimitarCC** [comment]
this commit here 91b2a429e731ae812a69da2b41d40364effb9fbb causes the code editor to not load. There is no errors but just i see a blank tab instead of code

**Comment by wmjordan** [comment]
@DimitarCC 
Thank you for keeping track of the code.
I am still working on it.

However, it was weird that you saw a blank tab without code, which had never occurred while I was testing on my side.

**Comment by wmjordan** [comment]
There's a new beta version which has fixed a few bugs.

**Comment by DimitarCC** [comment]
@wmjordan Recent commits fixed my problem. now all is working.

**Comment by fitdev** [comment]
I just noticed that Super Quick Infos do not display information about implemented interface for static abstract/virtual members if those members are not defined on the interface that the current type directly implements:

```cs

interface IBase<T> where T : IBase<T> {
  static abstract T Foo { get; }
}

interface IDerived<T> : IBase<T> where T : IDerived<T> {
  static abstract T Bar { get; }
}

struct ConcreteType : IDerived<ConcreteType> {
  public static ConcreteType Foo => default; // <-- SuperQuick Info DOES NOT DISPLAY Interface implementation info at all!
  public static ConcreteType Bar => default; // <-- SuperQuick Info correct displays that this member implements IDerived<T>.Bar
}
```

**Comment by wmjordan** [comment]
It is good on my side.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/12182730/236136105-1838e89c-a5b8-43e3-91bf-1339df60df92.png">

**Comment by fitdev** [comment]
I am very sorry. You are right. It was an oversight on my part. Sorry. And thank you for such a quick reaction. It works now correctly.

**Comment by wmjordan** [comment]
Good.
Please download the new beta and help test it :)

**Comment by fitdev** [comment]
One small thing. I noticed recently (not sure with which version it happened) that I cannot navigate to symbol definition from NaviBar if the symbol (type or member) is _not_ part of my solution, i.e. it comes from a library reference or from a framework. When I click on it in the NaviBar nothing happens. Yet I can navigate to its definition from VS code editor (by Ctrl-Clicking) to open either generated source from metadata or actual source via source link.

**Comment by wmjordan** [comment]
It did not happen to me.
I could click symbols within the `System...` namespace and some others from the NaviBar and it brought me to the decompiled source.

**Comment by fitdev** [comment]
In my case it does not work, even with the latest Codist beta. When I click on any type in the NaviBar popup, if the type is not a user code, nothing happens.

**Comment by wmjordan** [comment]
Please try to revert to older versions of Codist and see which one works.

**Comment by fitdev** [comment]
I am not using latest VS Preview right now so perhaps that's why. I will first wait till they release 17.7 Preview 1 and see if it still does not work there.

**Comment by wmjordan** [comment]
> I am not using latest VS Preview right now so perhaps that's why. I will first wait till they release 17.7 Preview 1 and see if it still does not work there.

It shouldn't be the case.
The go to source function works from VS 2017 through the latest VS preview with which I am working with.
BTW, I've just uploaded a new beta. Try your luck and see see.

**Comment by fitdev** [comment]
Thank you for the beta. The latest 8682 beta still has this issue - I cannot navigate to non-user-code sources from NaviBar.
Also, I noticed that after I installed this version my colors were screwed up in the text editor - the old problem has returned. I now have to once again go to Options, Text Editor, C#, Advanced, Editor Color Scheme: 2017 -> 2019, then back to 2017 (the theme I use), then the colors were restored.

**Comment by wmjordan** [comment]
Could you upload your config file here and let me test it?

**Comment by wmjordan** [comment]
> When I click on it in the NaviBar nothing happens. Yet I can navigate to its definition from VS code editor (by Ctrl-Clicking) to open either generated source from metadata or actual source via source link.

Do the links in Super Quick Info work for you?

**Comment by fitdev** [comment]
Latest beta crashed VS when I was switching to C# Interactive tool window:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.CSharpParser.VisualElement_IsVisibleChanged(System.Object, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyPropertyChangedEventHandler.Invoke(System.Object, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.RaiseDependencyPropertyChanged(System.Windows.EventPrivateKey, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.UpdateIsVisibleCache()
   at System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual, System.Windows.DependencyProperty)
   at System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty)
   at System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.UpdateIsVisibleCache()
   at System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual, System.Windows.DependencyProperty)
   at System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty)
   at System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.UpdateIsVisibleCache()
   at System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual, System.Windows.DependencyProperty)
   at System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty)
   at System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.UpdateIsVisibleCache()
   at System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual, System.Windows.DependencyProperty)
   at System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty)
   at System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.UpdateIsVisibleCache()
   at System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(System.Windows.Media.Visual, System.Windows.DependencyProperty)
   at System.Windows.FrameworkElement.InvalidateForceInheritPropertyOnChildren(System.Windows.DependencyProperty)
   at System.Windows.UIElement.OnIsVisibleChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.UIElement.UpdateIsVisibleCache()
   at System.Windows.UIElement.OnVisualParentChanged(System.Windows.DependencyObject)
   at System.Windows.Media.Visual.FireOnVisualParentChanged(System.Windows.DependencyObject)
   at System.Windows.Media.Visual.AddVisualChild(System.Windows.Media.Visual)
   at System.Windows.FrameworkElement.set_TemplateChild(System.Windows.UIElement)
   at System.Windows.Controls.ContentPresenter+UseContentTemplate.BuildVisualTree(System.Windows.FrameworkElement)
   at System.Windows.StyleHelper.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, System.Windows.FrameworkElementFactory, Int32, System.Collections.Specialized.HybridDictionary, System.Windows.FrameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.FrameworkElement)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by fitdev** [comment]
> Do the links in Super Quick Info work for you?

Yes, _all_ links work from Quick Infos, but only _some_ (usually from 3rd-party libs (not Framework)) work from NaviBar.

> This type of weirdness has disappeared after 7.3 for me.

They were all fine for me as well. Only the latest beta caused the issue (and I have not changed VS version or installed other extensions, so still using the same VS).

However as far as parenthesis highlighting goes, I have to change the highlight color from barely visible gray to a bright one every time I update Codist.

**Comment by fitdev** [comment]
> Could you upload your config file here and let me test it?

Here it is.
[Config.json.zip](https://github.com/wmjordan/Codist/files/11413339/Config.json.zip)

**Comment by wmjordan** [comment]
> Latest beta crashed VS when I was switching to C# Interactive tool window:
> 

Thank you for reporting the crash.
It can be a multi-threaded contention, which might also occur in 7.3, I am afraid.
The failure of syntax highlighting might also has something to do with this bug.
I will fix it.

However, I still have no idea about the malfunction in the NaviBar at this moment.

**Comment by wmjordan** [comment]
> Yes, _all_ links work from Quick Infos, but only _some_ (usually from 3rd-party libs (not Framework)) work from NaviBar.

If you revert Codist to 7.3, will this issue still occur?

**Comment by fitdev** [comment]
> It can be a multi-threaded contention, which might also occur in 7.3, I am afraid. The failure of syntax highlighting might also has something to do with this bug.

It happened just once. Other times when I would go to C# Interactive it did not happen.

> If you revert Codist to 7.3, will this issue still occur?

Yes, it is there in 7.3, 7.2, 7.1, 7.0. I did not notice it before because normally I either Ctrl+Click or navigate through Quick Info. It is only when I want to _explore_ a 3rd party namespace for example I resort to using NaviBar.

So far I cannot determine exactly when the issue occurs. It certainly never happens with any user code!
It also never seems to happen with the direct (first-level dropdown).
It usually happens with non-user code in the 2nd+ (3rd, etc.) NaviBar dropdowns (floating windows) when clicking on a non-user code item.
Interestingly, say when any type from a non-user namespace say `ExternalLib.Ns1.Ns2` is present in the active document when I use NaviBar (for example type `ExternalLib.Ns1.Ns2.Type1` is present in opened document code), then when I click on the NaviBar: House Icon -> ExternalLib -> Ns1 (in new floating window) -> Ns2 (in 2nd level floating window) -> Type2 (from Ns2), then it works! BUT: If I do: House Icon -> ExternalLib -> Ns1 (in new floating window) -> TypeC (from Ns1), assuming that no types from `ExternalLib.Ns1` are present in the document, nothing happens when I click on `TypeC` (`ExternalLib.Ns1.TypeC`).
Hope it helps.

And, btw, I still hope some day to have a Class-Explorer/Object-Browser like functionality from Codist in a dedicated tool window where I can explore all types - my own, framework's, and 3rd party.

> This type of weirdness has disappeared after 7.3 for me.

As I was trying older Codist versions to see if the NaviBar issue was there, I noticed that after I install an older version, all colors are correct. Then, when I upgraded to the latest beta again, all colors were still correct! So it happened just once. But still very strange.

**Comment by wmjordan** [comment]
> Yes, it is there in 7.3, 7.2, 7.1, 7.0

Oh, that's too bad. It never occurred on my computer, from any version combination of Codist or VS.

Could you try the "Find Members" command on the Quick Info and see whether clicking members on the members list can jump to their decompiled source or metadata source?
<img width="272" alt="image" src="https://user-images.githubusercontent.com/12182730/236674487-3a69430c-0255-4b96-b7fb-dd0276c04a01.png">
<img width="283" alt="image" src="https://user-images.githubusercontent.com/12182730/236674513-40e03920-db57-4ea1-bd9b-116d8486807c.png">

When "go to definition" is not working, could you try right clicking on the member and see how the context menu look? Also, please hover on the member and see how the symbol tooltip which appears on bottom or top of the floating list window.

**Comment by wmjordan** [comment]
Does "go to definition" fail on all your projects and solutions, or just some specific projects?
If only on some specific projects, please try to make a small project and let me see whether it can be reproduced on my side.

**Comment by fitdev** [comment]
> Could you try the "Find Members" command on the Quick Info and see whether clicking members on the members list can jump to their decompiled source or metadata source?

Interestingly his works! Even when I right click on a NaviBar's floating 2nd level window on a type, then choose find members, and then in the new floating window with members click on any member, then it works! However if in the previous floating window I click on the type, whose members I just found, then nothing happens! So it seems to affect only the types in NaviBar's floating windows.

**Comment by fitdev** [comment]
![Screenshot_20230507_150802](https://user-images.githubusercontent.com/8166847/236676522-0d706b41-80be-48e4-86d5-e5092b73a2af.png)
 For example, if I click on `Parallel` in the background floating window, nothing happens! But If I click on one of it's members (after I had done right-click, Find Members on it) in the foreground floating window, then everything works - it takes me directly to the member's source.

**Comment by fitdev** [comment]
> Does "go to definition" fail on all your projects and solutions, or just some specific projects?

Seems to affect all projects.

Also, I noticed that it mostly (perhaps only) affects types that reside in non-framework and non-nuget references, i.e. those added with `<Reference Include="assembly.dll" />`

**Comment by wmjordan** [comment]
@fitdev

> I noticed that it mostly (perhaps only) affects types that reside in non-framework and non-nuget references, i.e. those added with `<Reference Include="assembly.dll" />`

It is not the case on my computer. Symbols from any referenced assemblies can be located on my system.


> However if in the previous floating window I click on the type, whose members I just found, then nothing happens! So it seems to affect only the types in NaviBar's floating windows.

When this happens, how does the symbol tooltip look under the NaviBar? When you move your mouse on to the symbol, there should be a tooltip appear under the NaviBar. Could you see that?

**Comment by fitdev** [comment]
> When this happens, how does the symbol tooltip look under the NaviBar? When you move your mouse on to the symbol, there should be a tooltip appear under the NaviBar. Could you see that?

Yes, I can see the tooltip with Namespace, Assembly, and description.

And regarding my previous comment:

> For example, if I click on Parallel in the background floating window, nothing happens! But If I click on one of it's members (after I had done right-click, Find Members on it) in the foreground floating window, then everything works - it takes me directly to the member's source.

Unfortunately this behavior seems inconsistent. As now, even when I click on the found members in the Find Members floating window, it did nothing. So, sometimes it works, sometimes it does not. And as for types (not members) in the floating window they seem to never work, except if their namespace is referenced in the opened document. However Framework types almost always (I think of all my tests - always) worked! So only 3rd party references seem to be affected.

**Comment by wmjordan** [comment]
@fitdev 
The new beta should have fixed the crash in C# Interactive Window.
However, I still have no idea why go to definition command on C# NaviBar fails on your computer.

**Comment by fitdev** [comment]
> However, I still have no idea why go to definition command on C# NaviBar fails on your computer.

I will try to provide more information when I come across something new.

**Comment by wmjordan** [comment]
@fitdev 
Please download this [test version](https://github.com/wmjordan/Codist/files/11437268/Codist.zip) which will show a message box when the go to definition command fails.
Once it occurs, please copy the text and let me know which part goes wrong.

**Comment by fitdev** [comment]
A few more issues:

1. I noticed that when Codist is enabled, I make a selection in the text editor, and type over it with one of the open braces, like: `(` or `<`, instead of replacing the selection, it encloses the selection in the braces. It is rather annoying at times. Is this something that was recently added to Codist (when I disabled Codist to test if it was coming from Codist, I was back to normal behavior). If so, can this be turned off?
2. After I disabled Codist to test, it was no longer displayed in Visual Studio, so not sure how to enable it. Since I cannot uninstall it or enable it.

**Comment by wmjordan** [comment]
There's a new beta.

@fitdev
I got a vague idea about your problem. However I don't know how to reproduce it on my side yet.
Anyway, I was trying to improve the syntax correctness of the NaviBar and SmartBar.
Please download the new beta, test it and try your luck :)


> I make a selection in the text editor, and type over it with one of the open braces, like: `(` or `<` or `"`, instead of replacing the selection, it encloses the selection in the braces. It is rather annoying at times.

Yes. I am experimenting similar feature like [this extension](https://marketplace.visualstudio.com/items?itemName=reduckted.AutoSurround). I found it sometimes interesting but as you said, it is rather annoying at times. I got bothered by this feature as well. Thus I removed it from this beta.

**Comment by fitdev** [comment]
Thank you so much for continuing to look into this. I will test the new beta and let you know.

> Yes. I am experimenting similar feature like this extension. I found it sometimes interesting but as you said, it is rather annoying at times. I got bothered by this feature as well. Thus I removed it from this beta.

Perhaps there is a way to make it into an option, available with a certain key combination (though I am not sure which one). But that way we could have the best of both worlds!

**Comment by fitdev** [comment]
> Please download the new beta, test it and try your luck :)

Just tried it on the same member and got same result: `AForge.Math.Matrix3x3` works, while `AForge.Parallel` does not work.

**Comment by wmjordan** [comment]
> Just tried it on the same member and got same result: `AForge.Math.Matrix3x3` works, while `AForge.Parallel` does not work.

Sorry to see that.
Could you try to make a small demo project for me to test?

**Comment by wmjordan** [comment]
> Just tried it on the same member and got same result: `AForge.Math.Matrix3x3` works, while `AForge.Parallel` does not work.

I think I have found the way to fix this bug.
Please download the new beta.

**Comment by fitdev** [comment]
Thank you for the new beta. Still no luck - the same behavior.

However I tried more things and it appears that on _some projects_ `AForge.Parallel` works (I am simply testing it on this type for consistency of results), but in some projects it does not work, _despite the fact that all projects reference the library_, and all projects are open as part of the same solution (I work on a single solution with 70 projects or so).

**Comment by wmjordan** [comment]
Thank you for taking time to test it.

The result somewhat confirmed my assumption.
The `TryGoToDefinition` method, provided by Rosolyn, takes a symbol and a project to work. The symbol must be in the project.
The problem is that the type names which appear to be within a namespace actually may come from various assemblies, referenced by various projects. Codist did not store the relationship of the symbol and the project while populating the drop-down and it fetched active project and passed it with the symbol that you clicked to the `TryGoToDefinition` method. When the symbol and the project did not match, the method failed.
The last beta tries to find out the right project from related projects, thus in more situations, it works better than previous ones.

But as you see, there is still something missed. Thus the function fails occasionally.

**Comment by fitdev** [comment]
> The problem is that the type names which appear to be within a namespace actually may come from various assemblies

Yes, this is definitely my case. Anyways, thank you for all your hard work! It's ok if it misses a few types, I can get around that.

**Comment by wmjordan** [comment]
> > The problem is that the type names which appear to be within a namespace actually may come from various assemblies
> 
> Yes, this is definitely my case. Anyways, thank you for all your hard work! It's ok if it misses a few types, I can get around that.

I don't know whether it is because of [this issue](https://github.com/dotnet/roslyn/issues/46113).

Could you take a closer look into those symbols that can not be navigated to and see what they differ from the others?

**Comment by fitdev** [comment]
> I don't know whether it is because of this issue.

Don't think it is my case, because all my user code works. It is only 3rd party references (usually assembly dlls) that do not work.

> Could you take a closer look into those symbols that can not be navigated to and see what they differ from the others?

The problem is that the symbols were the same. In the same solution, accessing them from one project works, and accessing from another project does not work - it is the same symbol and the same solution. I have not yet figured out what is so different between the two projects that in one case it works and in the other case it does not work. The same assembly dll is referenced from both in the same way.

But at this point, I think you managed to fix most of the occurrences of this. So, don;t feel like you really have to fix it completely. I can live with the current way.

**Comment by wmjordan** [comment]
> Don't think it is my case, because all my user code works. It is only 3rd party references (usually assembly dlls) that do not work.

Yes, this is the most tricky point. I just managed to reproduce your situation inspired by the aforementioned issue in Roslyn. It is really complicated.

In project P, which references project A, B and etc.
B also referenced A.
I unloaded A from the solution.
So, all namespaces in A would come from the compiled assembly of A.
The weird thing then happened.
Most types in A were navigable, but one type within the same namespaces were not.
The assembly, displayed on the symbol tool tip of that type, was showing that it came from "another" assembly that does not have a file path.

**Comment by wmjordan** [comment]
The unnavigable type `X` on my side was conditionally compiled, only included in the .NET 4.0 target.
The project `P` was targeting a higher version framework, thus `X` should not be accessible from that project.

However, in `P`, a referenced assembly `RA` was compiled with the .NET 4.0 target and it referenced `A`. Thus, `X` sneaked into the results of namespace members with `RA`.
That was the whole story, I believe.

**Comment by fitdev** [comment]
Wow! Yes, it is very complicated. I am glad you were able to get into such corner case, since it may affect quite a number of people.
However it is definitely not my case either. In my case the _same_ type from the _same assembly_ referenced in the _same way (assembly.dll in both cases, no user code)_ can be navigated to from project A, and cannot be navigated from project B (all in the same solution and at the same time!). The tooltip on the NaviBar for the type is the same in both cases (there is _no_ source file information in both cases because type comes from a referenced assembly.dll).

**Comment by fitdev** [comment]
> Can you make a mock solution which has those two projects and the reference to that assembly, but with only essential source code that help reproduce this?

I will see if I can do this, but it is not very easy due to complex in msbuild setup etc. Plus I am not sure the issue will be there even when I do make such a solution, but I will post it here if I succeed with a repro. I think it may have something to do perhaps with a particular version of VS/ Roslyn I am using.

**Comment by fitdev** [comment]
> Can you access the unnavigable type from project B (input that type name in project B and press F12 to navigate to it)?

Yes, and AFTER I did that, then NaviBar was able to navigate to that type too! Very strange!

**Comment by wmjordan** [comment]
> However it is definitely not my case either. In my case the _same_ type from the _same assembly_ referenced in the _same way (assembly.dll in both cases, no user code)_ can be navigated to from project A, and cannot be navigated from project B (all in the same solution and at the same time!). The tooltip on the NaviBar for the type is the same in both cases (there is _no_ source file information in both cases because type comes from a referenced assembly.dll)

Do you still remember when [we developed the namespace dropdown list](https://github.com/wmjordan/Codist/issues/67) years ago?
We saw multiple instances of a "same" type/namespaces displayed in the list. They actually came from various projects or their references, and Roslyn considered them individual symbols. Eventually I programmed name based symbol comparer to merge them into one.

It might be the reason while the symbol and the project do not match. However, I still could not explain why the compensational measure (trying related projects with the symbol) still failed sometimes.

**Comment by fitdev** [comment]
> Do you still remember when we developed the namespace dropdown list years ago?

Of course! I love this feature! Incredibly useful!

I understand what you mean. Yes, this is another interesting aspect. However I think it would only apply to user code, and in my case user code always works. What was not working for me is a type from a referenced dll, and both projects referenced the same version of dll with the same file path, so there should only be a single version of any type coming from this dll regardless of how many projects reference it.

**Comment by wmjordan** [comment]
> I noticed that when Codist is enabled, and I make a selection in the text editor, and type over it with one of the open braces, like: `(` or `<` or `"`, instead of replacing the selection, it encloses the selection in the braces. It is rather annoying at times. Is this something that was recently added to Codist (when I disabled Codist to test if it was coming from Codist, I was back to normal behavior). If so, can this be turned off?

[such an "annoying" feature is being discussed](https://devblogs.microsoft.com/visualstudio/surround-selection-experiment/).

**Comment by DimitarCC** [comment]
@wmjordan It's a matter of point of view. For some annoying for others useful.
I personally like that feature. And if it is an optional, it can satisfy needs for all.

**Comment by wmjordan** [comment]
> @wmjordan It's a matter of point of view. For some annoying for others useful. I personally like that feature. And if it is an optional, it can satisfy needs for all.

At first I was attracted by that behavior, and I about an hour to implement that feature and even improved the behavior to support Chinese punctuations, surrounding multiple selections, keep selections after edit, etc. that I had not seem in other extensions.
But as @fitdev remarked, this feature became somewhat out of control when we select something and begin to type a "pairable" character and expect that character will replace the selection.

I withdrew that feature in later beta versions with the belief that the behavior of "auto-pairing" should be improved. Perhaps it is good when editing .txt or .md files, but when editing code files, the "automatic bonus" can bring us undesired annoyance.
