### ISSUE TITLE
Codist Beta 7.5

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#267]
## Download
[Codist 8895](https://github.com/wmjordan/Codist/files/11676030/Codist.zip)

[Codist 8874](https://github.com/wmjordan/Codist/files/11642652/Codist.zip)
[Codist 8868](https://github.com/wmjordan/Codist/files/11642006/Codist.zip)
[Codist 8866](https://github.com/wmjordan/Codist/files/11641644/Codist.zip)
[Codist 8856](https://github.com/wmjordan/Codist/files/11635593/Codist.zip)
[Codist 8854](https://github.com/wmjordan/Codist/files/11633580/Codist.zip)
[Codist 8839](https://github.com/wmjordan/Codist/files/11609766/Codist.zip)
[Codist 8836](https://github.com/wmjordan/Codist/files/11608093/Codist.zip)
[Codist 8829](https://github.com/wmjordan/Codist/files/11595214/Codist.zip)
[Codist 8826](https://github.com/wmjordan/Codist/files/11589416/Codist.zip)
[Codist 8820](https://github.com/wmjordan/Codist/files/11587534/Codist.zip)
[Codist 8813](https://github.com/wmjordan/Codist/files/11562871/Codist.zip)
[Codist 8802](https://github.com/wmjordan/Codist/files/11529843/Codist.zip)
[Codist 8779](https://github.com/wmjordan/Codist/files/11523841/Codist.zip)
[Codist 8777](https://github.com/wmjordan/Codist/files/11521792/Codist.zip)
[Codist 8762](https://github.com/wmjordan/Codist/files/11514483/Codist.zip)

## What's new
- General
   - [x] Added new command to list members for `EventArgs` derived parameter type in an event symbol
   - [x] Added a command in Symbol Analysis menu to list locations of namespaces
   - [x] Made metadata location possible to jump to file explorer when clicked in symbol list
- Super Quick Info
   - [x] A new option to show ordinary comment in symbol declaration (#264)
      The new option is by default turned off. You need to manually turn it on in the options page by checking the _Show ordinary comment_ checkbox;
      Now it is possible to view comments for local variables, local functions which are not supported by the XML documentation system:
      <img width="383" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/c06cea78-d4d3-4c96-b507-bfb2d913efa0">
   - [x] Hid "default" and "null" default value from signature on C# Quick Info
   - [x] Prevented symbol context menu from dismissing Quick Info or Smart Bar (#263)
   - [x] Fixed duplicated symbol signature in C# Interactive window
   - [x] Fixed an edge case which caused error in Quick Info
   - [x] Automatically reposition Quick Info to prevent it from hindering text selection in code editor
   - [x] Added a new option to delay the display of Quick Info (#270)
       <img width="522" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/945a8969-917f-4d44-b523-4986a72d5d9e">
   - [x] Used "Editor Tooltip" font and font size in "Fonts and Colors" setting to display Quick Info (#276)
   - [X] Changed Quick Info size limitation to the whole popup window
- Syntax Highlight
   - [x] Fixed C#: Attribute Notation syntax highlighting improperly depended on Braces and Parentheses settings (#265)
   - [x] Fixed some syntax styles were not changed when editor font was changed
   - [x] Improved performance of syntax highlight
- Scrollbar Marker
   - [x] Improved performance of symbol references marker (#268)
   - [x] Fixed a potential crash in symbol references marker (#269)
- Navigation Bar
   - [x] Fixed some potential crashes when syntax model was not ready
- Smart Bar
   - [x] Changed behavior of "Select Symbol in Document" command to select selected parts of symbol
   - [x] Moved Smart Bar out of left margin to keep it from hindering selecting lines
   - [x] Fixed a potential crash caused by wrap text

**Comment by wmjordan** [comment]
@fitdev

@indeedhelp has posted a very interesting request (#264).

Please download the beta and see how it works on your side.

**Comment by wmjordan** [comment]
Yes, I mostly use XML Doc as well.

But the new option can show comments on local variables and local functions, as well as other symbol kinds.
It is still good to being able to comment them and see them elsewhere, when the method is long and complicated.

My typical possible usages for other symbol kinds:
I sometimes write comments for certain types or members, which is limited to internal development only, not for publish. If we use XML Doc, then those comments will be leaked with the XML doc file, even if the commented symbol is internal or private. With this option on, our team can read those comments easier, without exposing them public.

**Comment by BachiMjavanadze** [comment]
Thank you! awesome extension!
can I bring here my feature requests? maybe you will Implement some of them:
[automatically close brackets and quotes](https://github.com/madskristensen/Surrounder/issues/5)
[auto complete on one tab click](https://github.com/cfognom/VSIntelliSenseTweaks/issues/4)
[Delete only highlighted comments](https://github.com/madskristensen/CommentRemover/issues/11)
[Colorize only surrounded brackets](https://github.com/madskristensen/RainbowBraces/issues/17)
[VarCodeLens Errors](https://github.com/AdmiralSnyder/VarCodeLensExtension/issues/1)

**Comment by yekanchi** [comment]
is it possible to change font and style of super quick info?

**Comment by wmjordan** [comment]
@yekanchi 
Please download the new beta.
You can change the font on Super Quick Info with the "Editor Tooltip" font setting in the "Fonts and Colors" dialog page.
Codist respects that setting now.

**Comment by yekanchi** [comment]
> @yekanchi Please download the new beta. You can change the font on Super Quick Info with the "Editor Tooltip" font setting in the "Fonts and Colors" options page. <img alt="image" width="521" src="https://user-images.githubusercontent.com/12182730/242145450-1aba68a1-1921-4f54-ad21-1bce6edfc209.png">
> 
> Codist respects that setting now.

awesome work.

**Comment by wmjordan** [comment]
There's a new beta version which better handles repositioning of Quick Info.

@yekanchi 
The just uploaded beta also respects font size setting of Editor Tooltip.

**Comment by wmjordan** [comment]
Hi everybody,

There's a new beta version which changes the size limitation of Quick Info to the whole popup window.
The current implementation limits the size of Quick Info sections.
If there are quite a few sections in the same Quick Info, the total size of the popup can add up to a large one.
<img width="467" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/19f028e5-affc-4ed5-810f-26050a5df5ad">

The new implementation limits the size of the whole Quick Info popup window.
No matter how many sections in the Quick Info, the popup will have a overall size limitation (configurable in the Options page).
<img width="467" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/1bfe8ec5-72bf-4b27-87aa-a5a06d0fd5ea">

The two implementation have their own pros and cons.
However, if both of them are put together, two levels of scrollbars in the same window will be ugly and unpleasant to work with, which should be avoid.
I'd love to hear your opinions, which implementation is better for you.

**Comment by fitdev** [comment]
This is a nice improvement. However, I would prefer a middle ground: have certain header and footer section be always visible, while the bulk of the tooltip - the description, attributes, interfaces / members behave in the new way (i.e. they all share a single vertical container with a single scrollbar).
The always visible header sections would be the actual header - everything what is displayed to the right of the button/icon in the top-left corner. While the visible footer sections I would like to see would be the Assembly and Namespace.

**Comment by IneedHelp** [comment]
> The always visible header sections would be the actual header - everything what is displayed to the right of the button/icon in the top-left corner. While the visible footer sections I would like to see would be the Assembly and Namespace.
+1 to this

**Comment by wmjordan** [comment]
@fitdev , @IneedHelp 
So you both are in favor of the new implementation that all stuff within Quick Info shares one scrollbar?

**Comment by fitdev** [comment]
> all stuff within Quick Info shares one scrollbar

Yes, except for the header and footer sections.

**Comment by IneedHelp** [comment]
@wmjordan Yes, same thoughts as @fitdev

**Comment by wmjordan** [comment]
There's a new beta which fixes a few odds in Super Quick Info.

**Comment by fitdev** [comment]
Thank you for the new beta. Right now the Header and Footer (with assembly and namespace) all share the same content box with a single scroll bar. Is it possible to make the header and footer sticky (fixed), such that they are always visible, and have only the middle sections share the same container and scrollbar?

**Comment by wmjordan** [comment]
yes, the new hack of quick info may bring new potential layout. by now, please test the beta for a few days to compare the new experience against the previous one.

**Comment by fitdev** [comment]
I hope you can make the header and footer fixed. If not I would prefer the previous design where they are always visible.

**Comment by wmjordan** [comment]
For me, the pro of the previous design is that it can limit item height, the con of it is that it does not limit the total height of the popup so the popup can still be too large.

From the above screenshots, we can see that the `CodistPackage` class has some attributes, base types, and implemented some interfaces in the first screenshot. When I want to check out the base type, I see it at the first glance.
In the second screenshot, we only see attributes, and the base type and implemented interfaces are invisible without scrolling down manually.

For me, even if there is a fixed header, I still prefer the former design.

**Comment by wmjordan** [comment]
@laicasaane
Can you join us and give your opinion to the new design of Super Quick Info?

**Comment by wmjordan** [comment]
> I hope you can make the header and footer fixed. If not I would prefer the previous design where they are always visible.

The part above the yellow line demonstrated in the following screenshot can be made fixed, I guess.
However, it can take considerable space in some cases.
<img width="425" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/f2998a43-3a95-4308-83a2-92e38c8efdd7">

**Comment by fitdev** [comment]
> The part above the yellow line demonstrated in the following screenshot can be made fixed, I guess. However, it can take considerable space in some cases.

But it is no worse than previous implementation and is more flexible in that the middle sections will share the scrollbar. And what about the footer? Is it possible to make that fixed too?

**Comment by IneedHelp** [comment]
Using the latest beta, I'm getting weird spacing issues, like this:

![image](https://github.com/wmjordan/Codist/assets/1366970/2efba9b3-2642-436d-ad2e-56140108e555)
![image](https://github.com/wmjordan/Codist/assets/1366970/9dd7892a-c247-49f5-8982-833386b43fa5)

Seems like it's double the height it needs to be. I didn't change any new settings, just left it as it was after install.

**Comment by wmjordan** [comment]
@fitdev 
The footer is possible too. However, with two parts fixed, there can be less space left for the scrolling part.

@IneedHelp 
Strange. I never meet with this.

1. Can you always reproduce the problem?
2. If you uninstall the current beta and reinstall a prior version, what's the earliest version that works for you?
3. Can you make a demo project for me to test?

**Comment by IneedHelp** [comment]
> @IneedHelp Strange. I never meet with this.

Me neither, it started with the latest betas.

1. I did more tests before uninstalling 8875, and yeah, I can always reproduce it, but it's more obvious when there's more than a line of documentation.

2. I reverted back to 8868 and the blank space issue is gone, but now it shows like this:
![image](https://github.com/wmjordan/Codist/assets/1366970/c75bed4a-dbe2-46d7-ace4-4e1191ca69a8)

3. It really happened anywhere, even a new project with nothing but a member with a bit more documentation.

**Comment by wmjordan** [comment]
Could you upload a dome project here?

**Comment by IneedHelp** [comment]
> Could you upload a demo project here?

It would be just an empty project. I can give you the specifics: VS 17.7.0 Preview 1.0, .NET 8 preview 4 project

>From your previous screenshot, the /// <summary>... parts at the bottom of the picture do not seem to be generated by Codist.

I haven't installed other extensions in a long time, I just recently migrated from NET 7 to NET 8.

**Comment by wmjordan** [comment]
.NET 8 is still previewing... I have no plan to support it at this moment.

If you disable Codist, what is displayed for that Test type?

**Comment by IneedHelp** [comment]
> What's the corresponding source code?

```
namespace WpfApp1
{
 

    /// <summary>
    ///  simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
    /// </summary>
    public class Test
    {

    }
}
```

I just tested on a fresh WPF project set to NET 7, I get the same stuff.

**Comment by IneedHelp** [comment]
Either way, if it's still displayed when Super Quick Info is disabled, it's probably something related to my machine. I should've tested more before reporting this. And it seems other people aren't experiencing this.

**Comment by wmjordan** [comment]
I could not reproduce this on my machine, with a .NET 7 project.
<img width="627" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/1414b17f-b1bb-4927-934a-aa7454201930">

The raw XML Doc should not be displayed on the Quick Info.

**Comment by IneedHelp** [comment]
Yeah, I falsely believed it's related to Codist since upgrading to the new betas, but it's probably something that happened before and I just started noticing it. I'm on a production machine so I can't go to deep with experimenting; I'll probably have to get on a virtual PC to test step by step.

>I will delete related comments about that problem later, since it is irrelevant to Codist.

Yeah, please do, and sorry for the false flag.

**Comment by fitdev** [comment]
> The footer is possible too. However, with two parts fixed, there can be less space left for the scrolling part.

Well that's good to know that it is possible. I understand that there will be less space for the scrolling part, but that's ok, since it will still be better than the old way where almost every section could end up having a scrollbar when it does not fit.

**Comment by wmjordan** [comment]
> > The footer is possible too. However, with two parts fixed, there can be less space left for the scrolling part.
> 
> Well that's good to know that it is possible.

BAD news.
I got `FatalExecutionEngineError` when I am trying to move the tooltip control into a custom control with header and footer.

**Comment by fitdev** [comment]
> I got FatalExecutionEngineError when I am trying to move the tooltip control into a custom control with header and footer.

If it proves to be too difficult I am actually happy with the previous style (where each section can have its own scrollbar if too long). But I really would like to be able to see both header and footer, so perhaps you can either make the new behavior optional, or just revert to the way it has always been.

**Comment by wmjordan** [comment]
Well, I have managed to put the signature onto the top of the Quick Info.
However, the footer is tougher than I expected and it will not be in the next version.
![image](https://github.com/wmjordan/Codist/assets/12182730/f44239c9-a6db-4563-8b0a-c8e614062647)

**Comment by wmjordan** [comment]
Well, I have managed to put the signature onto the top of the Quick Info.
However, the footer is tougher than I expected and it will not be in the next version.
![image](https://github.com/wmjordan/Codist/assets/12182730/f44239c9-a6db-4563-8b0a-c8e614062647)

**Comment by wmjordan** [comment]
Well, I have managed to put the signature onto the fixed part of the Quick Info.
However, the footer appears to be more difficult than I thought.
Thus it won't be there in this version.
I will do something to improve the header instead.

**Comment by fitdev** [comment]
That's great! Will this be optional though, or will it be the new style that cannot be turned off? I mean I am more than happy to stay on the old style as long as I can see namespace and assembly information right away.

**Comment by wmjordan** [comment]
> I am more than happy to stay on the old style as long as I can see namespace and assembly information right away

@fitdev 
Why the namespace and assembly information is so important to you?

**Comment by wmjordan** [comment]
What if the containing assembly and namespace appear in the signature part, which is fixed on top of the Quick Info?

**Comment by wmjordan** [comment]
OK. Understood.

**Comment by wmjordan** [comment]
Please test the new beta which has optimized the layout of the Super Quick Info.

**Comment by fitdev** [comment]
Wow! You managed to do it! Looks great! Thanks so much for all your hard work!

**Comment by IneedHelp** [comment]
Amazing job! Really good stuff!

**Comment by fitdev** [comment]
I noticed that lately since the latest beta there would be syntax highlighting issues like this, where syntax styles would fail to be updated even after waiting for like a minute and even after typing something:

![Screenshot_20230611_152140](https://github.com/wmjordan/Codist/assets/8166847/2f8fef28-cda7-4142-8238-6e4b25539c40)

**Comment by wmjordan** [comment]
> I guess it mostly has to do with commenting out code.

Yes, it is.
However, it is not a fault of Codist.
I disabled Codist and was still able to reproduce this issue.

<img width="473" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/bdf6ff28-4862-4336-8ec6-a763a47ce882">
