### ISSUE TITLE
Codist Beta 7.6

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#283]
## Download
[Codist 8918](https://github.com/wmjordan/Codist/files/11777742/Codist.zip)

## What's New
- Syntax Highlight
   - [x] Customization window now attempts to automatically select a style for _Selected Code_ (#282)
   - [x] Removed automatic application of Codist-built-in themes after first installation (#282)
   - [x] Reset button could not remove highlight settings (#282)

**Comment by fitdev** [comment]
Small suggestion: Is it possible to add a variant of _Find Derived Classes / Interfaces_, where only the classes / interfaces that _directly_ inherit are shown (not the entire chain, i.e. no grand-children, no great-grand-children, etc.)?

**Comment by wmjordan** [comment]
There's a new beta version which implements limited derivation search.
Press down Ctrl key before executing _Find Derived Classes_ or _Find Inherited Interfaces_ command.

**Comment by fitdev** [comment]
That's awesome! You are so fast! Thank you!

**Comment by fitdev** [comment]
Just tried latest beta. Does not seem to work for me - the list is always empty, even though there are several directly-derived classes in other assemblies (some abstract, some not).

**Comment by wmjordan** [comment]
It works for me. Can you make a sample solution?

<img width="416" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/fd0a0870-5b9c-4efe-8c19-3cb3d118cad3">

Left: Directly derived
Right: All derived

**Comment by fitdev** [comment]
The issue is when those derived classes are in _other assemblies / projects_ than the base class.

**Comment by wmjordan** [comment]
Please try the new beta.

**Comment by fitdev** [comment]
Still the same issue. If a derived class is in the same assembly, it shows up. If it is in different assembly, it does not show up. If however I search for all derived classes (previous default behavior) - they all show up.

**Comment by wmjordan** [comment]
It had something to do with generic classes.

OK, please download the new beta.

**Comment by fitdev** [comment]
Unfortunately it still does not work. And in my case there are no generic classes involved. Unfortunately as of yet I could not produce a repro that I can send, because it does work in the test solution I made with 2 projects.

So, perhaps you can just reuse the old code that lists all derived classes / interfaces, and then manually check each one if it is a directly-derived, and if it is keep it in the list (as opposed to trying to get only directly derived classes only in the first place).

**Comment by wmjordan** [comment]
Yes, it is what Codist is doing--find all derived classes first and filter them, keeping those which have type.BaseType = questionedType.

I have a solution that has multiple projects and the filter is doing its job without any problem.
The base type is in project A and some directly derived types in project A, some in project B and C.

**Comment by fitdev** [comment]
> Yes, it is what Codist is doing--find all derived classes first and filter them, keeping those which have type.BaseType = questionedType.

Oh I see. Very strange then. What filtering code are you using to get at directly-derived classes?

**Comment by wmjordan** [comment]
````C#
internal static async Task FindDerivedClassesAsync(this SemanticContext context, ISymbol symbol, bool directDerive) {
	var type = symbol as INamedTypeSymbol;
	var classes = await SymbolFinder.FindDerivedClassesAsync(type, context.Document.Project.Solution).ConfigureAwait(false);
	if (directDerive) {
		if (type.IsGenericType) {
			classes = classes.Where(t => {
				var bt = t.BaseType;
				return bt.Equals(type) || bt.IsGenericType && bt.OriginalDefinition.Equals(type);
			});
		}
		else {
			classes = classes.Where(t => t.BaseType.Equals(type));
		}
	}
	await SyncHelper.SwitchToMainThreadAsync(default);
	ShowSymbolMenuForResult(symbol, context, classes.ToList(), directDerive ? R.T_DirectlyDerivedClasses : R.T_DerivedClasses, false);
}
````

**Comment by fitdev** [comment]
Could you perhaps add some logging into this routine that will record fully qualified name of: `symbol`, and then all the `classes` (their fully qualified names, _and_ their `BaseType` fully qualified names)/ Maybe save this log in Codist's default settings location where Codists's settings are stored?

**Comment by wmjordan** [comment]
Somehow the `BaseType.Equals(type)` fails. The "qualified type names", I guess, won't help too much.

**Comment by fitdev** [comment]
That's what I thought. Which is why I thought it would be nice to see the actual lists that Roslyn gives for each case, including their base types. Just to see what we are comparing with what. Perhaps instead of qualified names, record location / project / assembly of the symbol in question?

BTW, this may also shed some light into other Roslyn-related / find-symbol-related areas as well - as to why they may fail too.

**Comment by fitdev** [comment]
I mean the idea is to have a text representation of each `BaseType` (its name, assembly / project, or whatever else uniquely identifies it) and `type` to see why `Equals` fails. Since you cannot repro this, the only way is for me to run this version on my end and see what the logs will display. Ideally logging of all `classes` would be good to include too.

**Comment by fitdev** [comment]
BTW: Do the latest beta version of Codist re-introduce parenthesis/quotes automatic surrounding of selected text issue? I noticed that my selection gets surrounded with `"`s when I type over it. This started happening once I updated Codist version. But I could find nothing in the options.

**Comment by wmjordan** [comment]
> Do the latest beta version of Codist re-introduce parenthesis/quotes automatic surrounding of selected text issue?

Yes. It does. A few users ask for that.
I change the way it works and I am working with that function turned on for quite some time now.
The previous implementation was somewhat trouble-making, but I seldom feel annoyed by the new implementation now.
Give it a try :)

**Comment by fitdev** [comment]
> Yes. It does. A few users asked for that.

Oh I see. Please make it optional. Right now it is very annoying.

**Comment by wmjordan** [comment]
> Right now it is very annoying.

Once the first character is typed, 
1. if no more characters are to be inserted after it, you can press Delete or Backspace key to remove the content.
2. if more characters are to be inserted after the first character, just keep typing.

On my side, situation 2 is far more frequent than situation 1. Thus I can tolerate situation 1.

Anyway, an option will be there in the next version.

**Comment by fitdev** [comment]
Thank you for explanation. I will give it a try. But glad to know that there will also be an option!

Does the new beta you just released contain any logging with regards to `FindDerivedClassesAsync`? I am really curious to see what the results are for my solution and why it may fail on `Equals`.

**Comment by wmjordan** [comment]
The previous implementation did not allow the above situation 2, and situation 1 required moving the caret, thus it was very very very annoying 😡 .
The new implementation tweaked the selection after auto-surrounding character pairs, and I found that I began to take advantage of the auto-surround behavior (situation 3) recently. Thus I decided to include it into the beta and let it receive some feedback.

That feature will by default turned off in the finally released version unless I found some better way to introduce the changes in the new version to the users.



> Does the new beta you just released contain any logging with regards to `FindDerivedClassesAsync`?

No. Not yet. The log will have to be quite verbose I guess. I need to figure out what to be logged.

**Comment by fitdev** [comment]
> I need to figure out what to be logged.

Ideally assembly / project name, file location (at least first code file in case of `partial`s), and symbol name (though name + namespace would be even better).

**Comment by wmjordan** [comment]
@fitdev 

Please try this beta, which generates some logs.
[Codist.logged.9057.zip](https://github.com/wmjordan/Codist/files/11925991/Codist.zip)

To activate the log and make Codist log to the log file:
1. Close VS.
2. Open the config.json file with a text editor,
3. Add `"LogPath": "D:\\log.txt",` into it, like the following code snippet shows. The log path can be any place that you can access.
4. Save the config.json file.
5. Open VS.
6. There might be something already logged into the log file.
7. Delete the log content in the file and save it, since the content there is not of your interest yet.
8. Execute the "Ctrl"ed _Find Derived Classes_ command.
9. Examine the log file. It should have some entries with ` != ` in it.

````json
{
  "Version": "7.5.0",
  "LogPath": "D:\\log.txt",
  "DisplayOptimizations": "HideSearchBox, HideAccountBox, ShowCpu",
.....
````

**Comment by fitdev** [comment]
Thanks so much. I will try it soon and let you know my findings!

**Comment by fitdev** [comment]
Just tried it. Unfortunately VS crashes when I attempted Ctrl+FindDerived:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.Controls.SymbolCommands+<>c__DisplayClass1_0.<FindDerivedClassesAsync>b__1(Microsoft.CodeAnalysis.INamedTypeSymbol)
   at System.Linq.Enumerable+WhereEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Codist.Controls.SymbolCommands+<FindDerivedClassesAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Codist.Controls.CSharpSymbolContextMenu+UIHost+<FindDerivedClasses>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

The log file was empty.

**Comment by fitdev** [comment]
> The new implementation tweaked the selection after auto-surrounding character pairs, and I found that I began to take advantage of the auto-surround behavior (situation 3) recently. Thus I decided to include it into the beta and let it receive some feedback.

Yes, the new approach is quite smart! I like how you handled the common cases. But what if I want to type just _one_ of the parenthesis _replacing selection_. Presumably I would have to hit `Delete` key twice? If that is the case, then I suggest that rule 1 is altered such that it will use default (overwrite) behavior - removing _not only_ the selected text but _also_ the 2nd parenthesis - which should occur automatically after either `Delete` or `Backspace` key was pressed the _first time_.

**Comment by fitdev** [comment]
Also, got another VS crash (unrelated to logging or Derived Classes thing) - apparently when it tried to display Super Quick Info:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.QuickInfo.QuickInfoOverrideController+QuickInfoPositioner.Reposition(Boolean)
   at Codist.QuickInfo.QuickInfoOverrideController+QuickInfoPositioner.QuickInfo_SizeChanged(System.Object, System.Windows.SizeChangedEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.FrameworkElement.OnRenderSizeChanged(System.Windows.SizeChangedInfo)
   at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by wmjordan** [comment]
I checked out the source code of Roslyn and found that there was no magic.
It always use `type.BaseType?.OriginalDefinition.Equals` alike method to compute the matched base type.

Please try the new beta and see whether it works.

**Comment by wmjordan** [comment]
> what if I want to type just _one_ of the parenthesis _replacing selection_. Presumably I would have to hit `Delete` key twice?

No. You don't need hitting Delete twice.
Select the content to be replaced. Type `(`, then hit Delete. The previous selected content and the automatically inserted `)` will be erased together.

Do NOT press Delete before typing `(`.
Otherwise, there will be an empty selection before typing `(` and Codist won't auto-surround the content.
When you type `(`. It is now VS which automatically inserts the `)` for you.
And you have to hit Delete once again.

**Comment by wmjordan** [comment]
There's another approach which displays class inheritance in a hierarchical view.

A quick and dirty implementation looks like the following:
<img width="220" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/3fdfaba7-961c-4044-a44b-7f96f0b0644e">

**Comment by fitdev** [comment]
> There's another approach which displays class inheritance in a hierarchical view.

This is awesome! I really like it!

**Comment by fitdev** [comment]
Tried the new beta. Directly-Derived Classes is empty once again. And log file is empty too. I guess this version has no logging. It would be nice to see the log, so can you please enable logging for this routine?

**Comment by wmjordan** [comment]
In short, the log would not help since the underlying conditions are complicated.

I reproduced the problem of BaseType comparison while I was developing the hierarchical result presentation.
In one test, I tried to find directly-derived classes for `System.Attribute`. In the temporary results, I observed at least 3 `System.Attribute` instances with the same looking but actually different containing assemblies (_mscorlib_).

Then I checked more thoroughly into the source code of Roslyn and found that special type comparison mechanism was used while searching for derived classes.
That mechanism was not publicly exposed via API. Thus we have to recreate our own wheel.

**Comment by fitdev** [comment]
Glad you were able to at least reproduce the issue on your end, as I could not produce a repro - it only occurs in my large solution. Hopefully the workaround won't be too difficult.

Though I do think that perhaps having some kind of logging mechanism for Roslyn-related stuff in Codist could be useful potentially to diagnose other kinds of issues, like the one from a few months back where symbols could not be navigated to in the NaviBar.

**Comment by wmjordan** [comment]
> symbols could not be navigated to in the NaviBar

While I am working on prerequisites for #231, this issue has been partially addressed in the previous beta and will get better dealt with in upcoming versions.

**Comment by wmjordan** [comment]
The new beta should be able to fix the missing classes in Find Derived Classes command.
Also, pressing Shift when executing the command will list the derived classes in hierarchical order.

A new button is also added to copy the symbol list content to clipboard.

**Comment by fitdev** [comment]
The new beta works great! Thank you so much for all your work! I really like the new hierarchical display of derived classes too!

**Comment by wmjordan** [comment]
> I really like the new hierarchical display of derived classes too!

Please help test the new hierarchical view by comparing its output with the one from the previous implementation.
If the number of the new view and the previous view equals, it probably works correctly. Otherwise, there might be something wrong with the new view.
You can use the _Copy List Content_ button at the top right corner of the window to copy the lists from bother views into the clipboard and use a text editor to unindent and sort the output, then use a diff tool, for instance, WinMerge, to compare the output from the new implementation against the original implementation.

**Comment by fitdev** [comment]
> Please help test the new hierarchical view by comparing its output with the one from the previous implementation.

I will keep an eye on this. So far the counts have matched, so it works really well. I will let you know if I come across inconsistencies.

**Comment by wmjordan** [comment]
@fitdev
Please download and help test the new beta.

I am going to release this version.
1. The _Auto Pair Punctuation_ feature should be off by default.
2. The hierarchical view for _Find Derived Classes_ will be the default view (Shift: revert to old behavior).
3. Potential crash when repositioning the Quick Info should have been fixed in the last beta.

**Comment by fitdev** [comment]
Both items work as they should! Really like the new derived classes representation!

**Comment by wmjordan** [comment]
> Really like the new derived classes representation!

Maybe there will be a tree view in the future version, so we can collapse and expand hierarchical items.

**Comment by fitdev** [comment]
That would be great or a multi-column list-view like control! I think though in general, (perhaps I even suggested it sometime ago in a separate issue), it would be nice to have improved sorting/filtering capability for the symbol list control (including the one used for NaviBar). Like ability to filter not just accessibility levels but kinds of classes - static, record, sealed, etc; kinds of members - extension, virtual, abstract, etc.
