### ISSUE TITLE
Codist 7.9 beta

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#316]
## Download 
[Codist 9886](https://github.com/user-attachments/files/15738992/Codist.zip)

[Codist 9884](https://github.com/user-attachments/files/15726320/Codist.zip)
[Codist 9881](https://github.com/user-attachments/files/15717263/Codist.zip)
[Codist 9869](https://github.com/user-attachments/files/15587485/Codist.zip)
[Codist 9861](https://github.com/user-attachments/files/15523962/Codist.zip)
[Codist 9859](https://github.com/wmjordan/Codist/files/15500141/Codist.zip)
[Codist 9848](https://github.com/wmjordan/Codist/files/15469465/Codist.zip)
[Codist 9846](https://github.com/wmjordan/Codist/files/15442037/Codist.zip)
[Codist 9840](https://github.com/wmjordan/Codist/files/15434231/Codist.zip)
[Codist 9838](https://github.com/wmjordan/Codist/files/15417231/Codist.zip)
[Codist 9822](https://github.com/wmjordan/Codist/files/15144818/Codist.zip)
[Codist 9808](https://github.com/wmjordan/Codist/files/15136252/Codist.zip)
[Codist 9743](https://github.com/wmjordan/Codist/files/14895558/Codist.zip)
[Codist 9635](https://github.com/wmjordan/Codist/files/14442348/Codist.zip)
[Codist 9589](https://github.com/wmjordan/Codist/files/14325294/Codist.zip)
[Codist 9584](https://github.com/wmjordan/Codist/files/14297743/Codist.zip)
[Codist 9583](https://github.com/wmjordan/Codist/files/14290686/Codist.zip)
[Codist 9573](https://github.com/wmjordan/Codist/files/14255763/Codist.zip)

## What's New
- General
   - [x] Add control to MessageWindow to suppress reoccurring exceptions
   - [x] Fix a crash in SymbolList
   - [x] Fix VS startup slowdown caused by Codist
   - [x] Don't throw exception if command is unavailable
- Syntax Highlight & Quick Info
   - [x] Implement support for new features in C# 12
- Syntax Highlight
   - [x] Support more language types in Comment Tagger
   - [x] Simplify configuration of semantic punctuations and operators
           ![image](https://github.com/wmjordan/Codist/assets/12182730/93bea9dc-e6fd-43cb-9741-34b75a5422c6)
   - [x] Tweak C# tagger to highlight more punctuations and operators
   - [x] Fix syntax highlight feature was not properly controlled
   - [x] Fix C# tagger not being enabled after syntax highlight feature was toggled on
   - [x] Exclude identifier from syntax highlighting due to the [VS classification type precedency bug](https://developercommunity.visualstudio.com/t/Identifier-has-too-high-priority-in-sy/10547451)
   - [x] Tweak order of type cast keyword in syntax highlight precedency
   - [x] Fix symbol source highlight not working as configuration change
   - [x] Enhanced highlight for Markdown documents
   - [x] Fix broken comment tagger (#328)
- Quick Info
   - [x] Fix some IAsyncQuickInfoSource instances not under feature control
   - [x] Fix Quick Info displaying above SmartBar, SymbolList when Super Quick Info is disabled
   - [x] Fix containing types not properly displayed for nested types
   - [x] Fix interface member implementations in base type list not correctly displayed on C# Quick Info
   - [x] Fix incorrect Quick Info for qualified C# constructors
   - [x] Fix incorrect captured variable info
   - [x] Bring back missing error icons in C# Quick Info for VS 17.10
   - [x] Auto adjust background color if document editor window background inverts
   - [x] Support inner text in `<see>` and `<seealso>` elements in C# XML Documentations (#327)
- Smart Bar
   - [x] Fix crash caused by CopySelectionWithoutIndentation when copying text without indentation from SmartBar
   - [x] Add buttons to Markdown SmartBar
- Code Analysis
   - [x] A new analysis command: parameter assignments (see #325)
- Navigation Bar
   - [x] Fix a crash caused by NaviBar
   - [x] Add buttons to MarkdownBar
- Refactoring
   - [x] Add Make Static refactoring
   - [x] Make seal refactoring work on C# records
   - [x] Fix incorrect insertion point in SealClassRefactoring and ChangeAccessibilityRefactoring
- Auto Pair Punctuation
   - [x] Add an option to trim selection before inserting paired punctuation
- Display
   - [x] Add option to hide Copilot button
   - [x] Retry if UI layout override fails on initialization

**Comment by laicasaane** [comment]
I've just upgraded to VS 17.9 and observed that Codist interferes with the default colorization. Disabling Codist will bring back the behaviour. My temporary solution is enabling syntax highlight of Codist.

**Comment by laicasaane** [comment]
With Codist syntax highlight enabled these types lose their color.
![image](https://github.com/wmjordan/Codist/assets/1594982/29e747fc-cc9e-433d-80b8-90d185fb35ea)

**Comment by wmjordan** [comment]
It is strange. I've been working with the 17.9 preview versions for quite a few months and things were fine after Codist 7.8. Does restarting your VS can make things work?

The following screenshot is taken after that I reset my Codist syntax highlight to default.
<img width="571" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/691782c1-19d0-4ecb-8c6f-fad11ed90596">
The following screenshot is taken after that I applied my Codist syntax highlight settings.
<img width="560" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/e412cfc8-d877-426e-a261-80b9af04ee2f">

Could you post a sample solution and let me test it?

**Comment by wmjordan** [comment]
@fitdev
There's a new beta version here which supports C# 12. Please help test it.

**Comment by fitdev** [comment]
Thank you for the new release! I will try it soon.

BTW, I have been using C# 12 for some time now, and have _not_ noticed any issues with Codist C#-wise. Out of curiosity - what was added in this beta version then?

Also, regarding syntax highlights being messed up - it happened to me on and off for the last 2 or so years - almost every time I would update VS. I am still on an older VS 17.9 preview for the time being, so I don;t know if the issue would affect me were I to upgrade top their latest 17.10 preview released yesterday.

**Comment by laicasaane** [comment]
Weird, it works now, and I've done nothing.

**Comment by wmjordan** [comment]
> what was added in this beta version then?

The new beta has supported highlight of collection expression, primary constructor of base type and the Quick Info of lambda expression return value.
The recently uploaded beta has added more language types to Comment Tagger and fixed some bugs.

**Comment by laicasaane** [comment]
Hi, it's acting up again. You can try this solution. It's just a source generator solution and you don't need Unity.
https://github.com/Zitga-Tech/ZBase.Foundation.Aliasing/tree/main/Packages/ZBase.Foundation.Aliasing/Source~

**Comment by wmjordan** [comment]
@laicasaane 
Could you zip that solution files and upload it here?

**Comment by laicasaane** [comment]
Here is the solution:
[ZBase.Foundation.Aliasing.SourceGen.zip](https://github.com/wmjordan/Codist/files/14292510/ZBase.Foundation.Aliasing.SourceGen.zip)

And the recent screen recording:
https://github.com/wmjordan/Codist/assets/1594982/b6fdc4ba-ff3a-4f0a-9d59-f3c9340043c5

**Comment by laicasaane** [comment]
For completeness, this is my Codist settings:
[Codist.json](https://github.com/wmjordan/Codist/files/14292520/Codist.json)

**Comment by wmjordan** [comment]
@laicasaane 
With your configuration file, I managed to reproduce your issue.
Some part of the advance syntax highlight procedure in Codist was ran despite of the disabled feature control.
And [a bug in VS's highlight](https://developercommunity.visualstudio.com/t/Identifier-has-too-high-priority-in-sy/10547451) was triggered after that procedure.

At this moment, you have to enable the Syntax Highlight feature in Codist and try your luck.

**Comment by laicasaane** [comment]
I'm OK with enabling Codist syntax highlight feature atm. However, this happens: https://github.com/wmjordan/Codist/issues/316#issuecomment-1942922465

**Comment by wmjordan** [comment]
Oh, bad luck.
You seemed to have encountered the aforementioned VS highlight bug that `identifier` was taking too high de facto priority.

**Comment by wmjordan** [comment]
It is really strange.

**Comment by wmjordan** [comment]
@laicasaane 
You'd been bugged by the aforementioned VS highlight problem.
Please re-enable the syntax highlight feature and clear the foreground color of the `identifier` in the Syntax Highlight Customization Window.

**Comment by laicasaane** [comment]
![image](https://github.com/wmjordan/Codist/assets/1594982/36c410b0-e63f-4d95-9f99-bb3947fd0847)
Shouldn't `=>` be categorized as operator instead of `C#: Method`? Is this the bug in VS highlight too?

**Comment by wmjordan** [comment]
> Shouldn't `=>` be categorized as operator instead of `C#: Method`? Is this the bug in VS highlight too?

I deliberately changed the style of `=>` operators in member declarations to indicate the declaration type.

**Comment by wmjordan** [comment]
There's a new beta version for test.

The configuration window for syntax highlight has simplified the punctuation highlight options.
![image](https://github.com/wmjordan/Codist/assets/12182730/93bea9dc-e6fd-43cb-9741-34b75a5422c6)

**Comment by fitdev** [comment]
So does the new behavior extend the previous options to also apply to operators? Previously it was only for "Braces and Parentheses".

**Comment by fitdev** [comment]
In the latest beta operator overloading does not seem to work:
![Screenshot_20240229_220206](https://github.com/wmjordan/Codist/assets/8166847/94d56f88-b6d5-4052-92da-ea0e52a9e149)

**Comment by wmjordan** [comment]
> In the latest beta operator overloading does not seem to work

It is a bug in VS.

You can reproduce the problem with Codist disabled.
<img width="583" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/fe1e7564-3fda-477a-8542-d1553a871834">

**Comment by wmjordan** [comment]
Hi, everybody.

There's a new beta which enhances highlight (three more syntax styles for customization) and editing of Markdown documents.

**Comment by fitdev** [comment]
> three more syntax styles for customization

Which ones are those?

**Comment by wmjordan** [comment]
There is a new test version which addresses VS startup slowdown caused by Codist, reported from the Performance Manager.

**Comment by wmjordan** [comment]
The previous 9788 build could crash VS. Please download the newly uploaded 9798 build.

**Comment by wmjordan** [comment]
Oops, 9808 should fix the crash.

**Comment by fitdev** [comment]
I am not sure if has worked correctly in Codist before, and perhaps is no longer working now, but there seems to be an issue with "Find Referrers" command for implicit operators. They only seem to find the cases of direct casts, with implict casts not being returned:

```cs

struct Foo {
public static implicit operator Foo(int i) => new Foo();
}

class Usage {

void Test() {
  Foo foo1 = (Foo)25; //This is found
  Foo foo2 = 34; //This will not be found
}

}

```

Also there is a slight issue where implicit/explicit operators do not have super quick infos for them, they are only selectable using NaviBar.

**Comment by fitdev** [comment]
Oh I see - it is a Roslyn issue. Sorry for the comment then. Hopefully they will address it soon.

**Comment by wmjordan** [comment]
@fitdev 
You are welcome.
It takes quite some considerable calculation to find out implicit conversion.

In short, use implicit conversion sparingly and do not do expensive or complicate works within it.

**Comment by fitdev** [comment]
> In short, use implicit conversion sparingly and do not do expensive or complicate works within it.

I find them extremely useful, especially for "smart" arguments, where the _caller_ may use several different types depending on the need - like an int, or a string, or an enum (in this example for a user-defined TextEncoding type which can be initialized from a set of known encodings, a codepage, and encoding name for example) - all of which get auto-converted to the proper type though these implicit operators. So I wish Roslyn would fix it and allow one to see all instances of implicit conversion taking place.

**Comment by wmjordan** [comment]
> for "smart" arguments

It is possible to detect this type of situations in the _Find Parameter Assignment_ function though.
Please try the new beta.
It adds a type cast icon to the occurrence if the parameter is taken via implicit type conversion.

Please check whether the detection hurts the performance of that function.

**Comment by fitdev** [comment]
> It is possible to detect this type of situations in the Find Parameter Assignment function though.

Thank you for the new beta! I am not sure though if it is of much help in finding implicit operator usages, since typically there would be 10s of methods - all accepting the same "Smart"-Struct-Typed argument with possibly 100s of usages across all these methods. But being able to see such implicit conversion in the Parameter Assignment list is very nice nonetheless, thank you!
