### ISSUE TITLE
Codist 5 Beta Version

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#81]
This thread focuses on the upcoming version 5 of Codist.
Newest released test version will be posted here.

New features planned or working-in-progress (unchecked) and implemented (checked) since version 4.6.2 are listed below:

- [x] A rewritten symbol list for Navigation Bar and Smart Bar (#79)
  - [x] Drag and drop to rearrange members in symbol list of Navigation Bar (#49)
  - [x] Better performance (#65)
  - [x] Scroll to current member when symbol list is displayed
  - [x] Right click context menu
  - [x] Code statistics on member kinds and line count (#48)
  - [ ] Better control to tool tip display
- [x] Hot keys to bring out menus in Navigation Bar (see Options page for default shortcuts) (#77)
- [x] Improved Quick info:
  - [x] Override captured variables info
  - [x] Quick info for parameter attributes (#78), method return type attributes, delegate signatures
  - [x] Size controller for all Quick Infos (previously C# only)
  - [x] Right click to copy contents (#76)
  - [x] Selectable diagnostics content
  - [x] Compatible to VS 16.1
  - [x] New alternative style
  - [x] New option to add extra height to XML Doc info
  - [x] Fix Quick Info contents out of sync with documents
  - [x] Fix an error due to `null` references in `Attribute`s
  - [x] Alter line margin in multi-paragraph Quick Info content
- [x] Improved Syntax Highlight:
  - [x] Highlight `volatile` fields
  - [x] Fix multi-line strings in `Attribute`s not correctly classified
  - [x] Fix foreach braces not correctly highlighted when direct tuple deconstruction was used
- [x] Improved Smart Bar
  - [x] Preview `KnownImageIds` in Find Members command (for VS extension developers)
  - [x] Show "Uncomment" command when necessary
  - [x] A new "Find referenced symbols" command
  - [x] Include constructors in "Find Members" command
- [x] Scrollbar Marker
  - [x] Fix broken preprocessor marker
  - [x] Add a `#region` marker
- [x] Option to display build start and end time
- [x] Option to auto increment manifest version of VSIX (for VS extension developers)

The new version will be released in the recent future. Please download the test version and post your issues below.

[Codist beta 5.0.0.4158](https://github.com/wmjordan/Codist/files/3219264/Codist.zip)

[Codist beta 5.0.0.4153](https://github.com/wmjordan/Codist/files/3216895/Codist.zip)
[Codist beta 5.0.0.4108](https://github.com/wmjordan/Codist/files/3209897/Codist.zip)
[Codist beta 5.0.0.4106](https://github.com/wmjordan/Codist/files/3206102/Codist.zip)
[Codist beta 5.0.0.4102](https://github.com/wmjordan/Codist/files/3205457/Codist.zip)
[Codist beta 5.0.0.4074](https://github.com/wmjordan/Codist/files/3196256/Codist.zip)

**Comment by fitdev** [comment]
Just got a VS Crash:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Windows.Media.VisualCollection.Add(System.Windows.Media.Visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(System.Windows.UIElement)
   at System.Windows.Controls.UIElementCollection.Add(System.Windows.UIElement)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(System.Object)
   at Codist.QuickInfo.QuickInfoOverrider+Default+Overrider.FixQuickInfo(System.Windows.Controls.StackPanel)
   at Codist.QuickInfo.QuickInfoOverrider+Default+Overrider.OnVisualParentChanged(System.Windows.DependencyObject)
   at System.Windows.Media.Visual.FireOnVisualParentChanged(System.Windows.DependencyObject)
   at System.Windows.Media.Visual.AddVisualChild(System.Windows.Media.Visual)
   at System.Windows.FrameworkElement.set_TemplateChild(System.Windows.UIElement)
   at System.Windows.Controls.ContentPresenter+UseContentTemplate.BuildVisualTree(System.Windows.FrameworkElement)
   at System.Windows.StyleHelper.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, System.Windows.FrameworkElementFactory, Int32, System.Collections.Specialized.HybridDictionary, System.Windows.FrameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(System.Windows.UncommonField`1<System.Collections.Specialized.HybridDictionary[]>, System.Windows.FrameworkElement)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Controls.Border.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement, System.Windows.Size)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Controls.StackPanel.StackMeasureHelper(System.Windows.Controls.IStackMeasure, System.Windows.Controls.IStackMeasureScrollData, System.Windows.Size)
   at System.Windows.Controls.StackPanel.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement, System.Windows.Size)
   at System.Windows.Controls.ItemsPresenter.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Controls.Border.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Controls.Control.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement, System.Windows.Size)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Controls.Border.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Controls.Control.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Controls.Decorator.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.Controls.Primitives.PopupRoot.MeasureOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
   at System.Windows.UIElement.Measure(System.Windows.Size)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by wmjordan** [comment]
The above crash has something to do with the Quick Info.
Could you reproduce it and post the code where you hover the mouse on?

**Comment by fitdev** [comment]
The crash happens when I hover over `File` in `File.WriteAllBytes(string, byte[])` when `using Alphaleonis.Win32.Filesystem;` (instead of `using System.IO;`). `Alphaleonis.Win32.Filesystem` has the same signatures as `System.IO` but allows for additional features on Windows, that's why I am using that instead. As soon, as I replace the using with the `System.IO` one, no crash happens and the quick info is displayed. When I change using back to `Alphaleonis.Win32.Filesystem` and hover over `File`, VS crashes completely.

**Comment by fitdev** [comment]
Another small issue is with `{` and `}` colorization in `foreach` in this case:

![2019-05-22 09_21_17-workspace net - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/58152031-22003400-7c74-11e9-856d-109f0df4f109.jpg)

Apparently when using tuple deconstruction `var (data, profileid, file)` instead of just `var x` it causes braces not to be colored properly.

**Comment by wmjordan** [comment]
> The crash happens when I hover over `File` in `File.WriteAllBytes(string, byte[])` when `using Alphaleonis.Win32.Filesystem;` (instead of `using System.IO;`).

I could not reproduce it on my computer.
What's the version of your AlphaFS?

![捕获](https://user-images.githubusercontent.com/12182730/58152940-630e3d80-7ca0-11e9-8381-f8292c57fa55.PNG)

**Comment by wmjordan** [comment]
> The crash happens when I hover over `File` in `File.WriteAllBytes(string, byte[])` when `using Alphaleonis.Win32.Filesystem;` (instead of `using System.IO;`).

OK. Thanks for the information.
I could reproduce the crash now. I checked out the XML Doc of the class and found that the problem was pretty weird and scarce.
There are **two** `<summary>` elements in the  XML Doc for the `File` class.
If you remove any one of them, no more crash.

**Comment by fitdev** [comment]
I am using v. 2.2.6. Glad you found the culprit! That is weird. I suppose the easiest fix for such cases would be to display no xml doc at all - or display a note stating that there was an error parsing xml doc, after all xml doc errors might not be that rare, so similar errors might happen in the future - with both user code, and external packages.

**Comment by wmjordan** [comment]
Please try the new beta 4106.

**Comment by fitdev** [comment]
Works great - no more crash! But the syntax colorization for `foreach` I described above is still missing.

**Comment by wmjordan** [comment]
> when using tuple deconstruction `var (data, profileid, file)` instead of just `var x` it causes braces not to be colored properly.

Is this new syntax in C# 8?

**Comment by fitdev** [comment]
Yes, I think so. It has to do with direct tuple deconstruction (either a value-tuple itself, or any deconstructable type with accessible deconstructors). In my example the `T` in `IEnumerable<T>` over which I am foreafching is a value tuple of `(string, int, FsFile)`

**Comment by fitdev** [comment]
Another small thing... This is the largest tooltip I have ever seen:

![2019-05-22 17_50_49-](https://user-images.githubusercontent.com/8166847/58184810-7c23e800-7cba-11e9-9f56-6874963f287d.jpg)

So, perhaps for cases with excessive XML documentation, that section of the quick info tooltip can be made scrollable, and the whole tooltip itself be smaller?

**Comment by wmjordan** [comment]
> This is the largest tooltip I have ever seen

You can limit the size a doc item takes by changing the _Max Height_ option in the Options page for Super QUick INfo

**Comment by wmjordan** [comment]
> direct tuple deconstruction

It is a syntax introduced in C# 7. I can support it. Please try the updated beta.

**Comment by fitdev** [comment]
Works great now! Thank you for a quick fix. Sorry about the quick info tooltip - I didn't realize height restriction is already implemented - should have looked in the options first.

**Comment by fitdev** [comment]
Another small thing with Quick Info and `<inheritdoc />`: **Returns** section is not displayed on the tooltip for the `<inheritdoc />` member (only summary is displayed):

![2019-05-24 10_23_18-workspace net - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/58310059-6cb5b380-7e0e-11e9-9d3d-e51e6ecda8e8.jpg)

![2019-05-24 10_23_55-workspace net - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/58310092-793a0c00-7e0e-11e9-9ba6-c3c956e9ca12.jpg)

**Comment by fitdev** [comment]
Another small syntax highlighting issue with operator overloads:

![2019-05-24 14_59_36-workspace net - Files cs](https://user-images.githubusercontent.com/8166847/58326238-e365a780-7e34-11e9-8cd8-3a25e0bed3f6.jpg)

The `/` operator is highlighted differently in exactly the same code depending on the surrounding code (inside of argument vs inside of variable assignment).

**Comment by wmjordan** [comment]
> **Returns** section is not displayed on the tooltip for the `<inheritdoc />` member

> The `/` operator is highlighted differently in exactly the same code depending on the surrounding code (inside of argument vs inside of variable assignment).

Please try the new beta.

**Comment by fitdev** [comment]
Everything is fixed now! Thank you for the quick fixes (I hope you don't mind me reporting such minor issues).

**Comment by wmjordan** [comment]
Great to hear that. Thank you for your thorough test and great suggestions.
Version 5 will be released in a few days.

**Comment by wmjordan** [comment]
The new version added a new option to show line of code counter on tool tips for members on Navi Bar (#48). Please give it a try.

**Comment by fitdev** [comment]
Thank you for pointing this out! This is a nice addition.

**Comment by fitdev** [comment]
Got a VS crash when hovering over one of the items in the NaviBar's dropdown:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at Microsoft.VisualStudio.Text.Implementation.UnaryStringRebuilder.GetLineNumberFromPosition(Int32)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineNumberFromPosition(Int32)
   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.GetLineNumberFromPosition(Int32)
   at Codist.TextEditorHelper.GetLineSpan(Microsoft.VisualStudio.Text.ITextSnapshot, Microsoft.CodeAnalysis.Text.TextSpan)
   at Codist.Controls.SymbolList.CreateItemToolTip(System.Windows.Controls.ListBoxItem)
   at Codist.Controls.SymbolList.ShowToolTipForItem(System.Windows.Controls.ListBoxItem)
   at Codist.Controls.SymbolList.MouseMove_ChangeToolTip(System.Object, System.Windows.Input.MouseEventArgs)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

The item thta crashed the VS was an extension method on `string` defined in another file (from the point of view of the active document, i.e. - partial static class):

```cs
    [DebuggerStepThrough, MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool StartsWithLower(this string str, char chr) => !string.IsNullOrEmpty(str) && char.IsLower(str[0]);
```

**Comment by fitdev** [comment]
I can confirm that the crash is most likely related to one-line methods written with `=>` syntax. Just got another crash on a different single-line method.

**Comment by wmjordan** [comment]
Thank you for the bug report.

> partial static class

The crash was due to the above reason. Please try the new beta.

**Comment by fitdev** [comment]
Thank you! Yes, the latest version fixed the issue.
