### ISSUE TITLE
Codist 5.3 Beta Version

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#94]
Beta test was closed.

- [x] General
  - [x] An info bar would be shown after version update
- [x] Symbol Analysis
  - [x] Made Find Callers command work for fields and attribute constructors
- [x] Syntax Highlight
  - [x] Enhanced highlight for type cast related keywords and parentheses (#96)
  - [x] Highlighted C# overload operator and destructor punctuation
  - [x] Fixed hanging and performance problem during syntax style changes (#100)
  - [x] Significant performance boost by reducing redundant classification operations in C# documents
- [x] Smart Bar
  - [x] Customizable web search engines
![shot](https://user-images.githubusercontent.com/12182730/63136956-ef619f80-c006-11e9-8fde-1bf9311a475b.png)
![shot](https://user-images.githubusercontent.com/12182730/63137110-6b5be780-c007-11e9-9239-f4f64a519655.png)
- [x] Navigation Bar
  - [x] ~Neighbor types~ Types referenced by current member (optional)
![shot](https://user-images.githubusercontent.com/12182730/63137196-b37b0a00-c007-11e9-9990-7f10c43332a7.png)
  - [x] Optional display of `#region`s within type members (#97)
  - [x] Themed foreground text of active function for better textual contrast (#98)
  - [x] Fixed crashes after drag&drop operations between partial type files (#99)
  - [x] Optimized scrolling speed when dragging Navigation Bar items within drop down menu
- [x] Super Quick Info
  - [x] Dimmed similar parts in method overloads
![shot](https://user-images.githubusercontent.com/12182730/63137463-f7bada00-c008-11e9-9d68-22e4e1e53da5.png)
  - [x] Shift+Click to open source code file for symbol in new window
  - [x] Compatible with VS 2019.3 preview 2, suppressed VS hyperlinks in Quick Info in Alternative Style (#102)
  - [x] Click and Go worked on imported symbols (symbols from metadata)
![shot](https://user-images.githubusercontent.com/12182730/63137556-5718ea00-c009-11e9-80bc-974e6b1da67d.png)
  - [x] Fixed duplicated Selection Quick Info in the C# Immediate window
  - [x] Option to display `<seeAlso>` of overridden XML Doc in Super Quick Info
- [x] Symbol List
  - [x] Clicking on imported symbol in the list could jump to its definition too
- [x] Scrollbar Marker
  - [x] Fixed an occasional crash (#101)

And many bug fixes and enhancements
